### ISSUE TITLE
Allow text to flow under minimap

### ISSUE THREAD

**Issue by AdiCheo** [atom-minimap/minimap#147]
![clipboard01](https://cloud.githubusercontent.com/assets/5605624/4957144/d270f29a-66a1-11e4-8306-9934a422a3b4.png)
![clipboard02](https://cloud.githubusercontent.com/assets/5605624/4957143/d269f7ce-66a1-11e4-8ed8-7f6a252a4ee8.png)

**Comment by fundon** [comment]
It's not reproduced in the latest Atom(v0.182) and Minimap(v4.3.1).

**Comment by abe33** [comment]
Closing as there's nothing new here.
