### ISSUE TITLE
Minimap is blank in the middle of files.

### ISSUE THREAD

**Issue by joytrekker** [atom-minimap/minimap#181]
This bug has been showing up since the first time installed Atom a few months ago. See the screenshot below. I just installed the newest version 0.157.0 with the windows installer and the problem persists. If I resize the window then the missing part of the minimap flashes on the screen. If I resize the window just right then it shows up properly. Large files have multiple sections that are blank. The Hardware Acceleration option has no effect. 

![Atom minimap error](http://i.imgur.com/IkXfFkd.jpg)

**Comment by abe33** [comment]
I think I'll publish a v3.0.5 soon that will include a preview of v4. It'll be interesting to see if you get this issue with the new version (so far I haven't encountered it with v4, but my testing environment is not as representative as it should).

**Comment by abe33** [comment]
v3.5.0 is out, if you want to try the incoming v4 version you can do it by activating the corresponding `V4 Preview` setting. Please tell me if the problement still occurs with this version.

**Comment by joytrekker** [comment]
I just tested v3.5 and unfortunately the problem persists. I also tested the v4 preview and bug is even worse. No code shows appears the minimap when a files is opened. If I scroll the minimap only a small section of the top of my file shows up. The minimap is also half the horizontal size it should be. See the screenshot below.
![Minimap Bug](http://i.imgur.com/Gh2C6da.jpg)

**Comment by abe33** [comment]
There must be something about your config/environment that doesn't play nice. Maybe something OS-related as I haven't heard anyone having this issue on OSX or linux (maybe I'm wrong about that but it seems like it).

About the half size, what gives the `atom-text-editor-minimap` node in the inspector? If you have a preferred line length and soft wrap enabled it should sets the width based on this config (there's no need to have a bigger canvas in that case). but maybe there's some pollution of some kind (flex layout is really awkward by moment).

**Comment by joytrekker** [comment]
Yes I think this is a Windows only bug. I'm on Windows 7 with an AMD Radeon card. I have tested the previous build on both OSX and Linux and there was no problem. 

I think I found the issue with half size problem. The `minimap-controls` node is given the width of the canvas instead of the width of the `minimap-visable-area node`   It is also interesting that when I open the inspector the minimap code preview works as expected. If I popout the inspector then the bug returns. So changing the height of the window is triggering something. I tried changing the width and it had no affect.

**Comment by abe33** [comment]
Thanks for taking the time to dig into this, I'll install a win7 a VM to test things when I'll get back home. 

If you feel to tweak things a bit, you can comment [these lines](https://github.com/fundon/atom-minimap/blob/master/lib/mixins/canvas-drawer.coffee#L21-L26) and put a `@drawLines(@context, firstRow, lastRow, 0)` instead, it'll basically deactivates the use of the offscreen canvas, redrawing every lines on each render, performances may drop a bit but the problem should disappear (this is a temporary hack until I get the solution to that problem)

**Comment by fundon** [comment]
Is there still this problem in the latest Atom(v0.182.0) and Minimap(v4.3.1)?
@joytrekker @Moter8 @JorgeGT

**Comment by JorgeGT** [comment]
It appears to be fixed for me =)

**Comment by joytrekker** [comment]
Just tested it again and bug is fixed. Atom 0.177.0 and minimap v4.3.1 on windows 7

**Comment by fundon** [comment]
Thanks guys. :)
