### ISSUE TITLE
Remove to atom-minimap org?

### ISSUE THREAD

**Issue by fundon** [atom-minimap/minimap#217]
Move this project to https://github.com/atom-minimap
How do you think? @abe33

**Comment by abe33** [comment]
Yes I think it would be appropriate, we'll have to make sure that people continue to get notified of update, do you have some knowledge about that?

**Comment by fundon** [comment]
Yes, people continue to get notifications that very important. At the moment , I don't know what is happen when we transport it to ORG?
I'm research.

**Comment by abe33** [comment]
I think we get close to the point where v4 will be ready for a release. It'll be the right moment to make the switch to atom-minimap.

**Comment by fundon** [comment]
Agreed.

**Comment by fundon** [comment]
Renamed repo-name, without `atom-` prefix.
Thanks again. @mark-hahn

**Comment by fundon** [comment]
@abe33 Happy Chinese new year!

I will transfer it to https://github.com/atom-minimap in few days.
And which's better the ORG name? `atom-minimap` or `atomminimap` .

**Comment by abe33** [comment]
Happy chinese new year too!

I'd rather go with `atom-minimap`, the org already exists and it fit with `atom-community` org too.

**Comment by fundon** [comment]
Transfered and released as v4.3.0.

**Comment by abe33** [comment]
:+1: Nice, I think I'll move the plugins as well soon, can you details the process you use for the change ? 

Note: I noticed that the update was detected by apm event with a change of repo, so I think your way of doing the change is quite right, so it would be great to document it for later use.

**Comment by fundon** [comment]
@abe33 

My steps

0. Remove `atom-minimap/atom-minimap` repo

0. Transfer `fundon/atom-minimap` to `atom-minimap/atom-minimap`

0. Rename `atom-minimap/atom-minimap` to `atom-minimap/minimap`

0. Update files about `repo name`

0. Publish new version

**Comment by abe33** [comment]
:+1: Thanks buddy, I'll make a test with minimap-selection (I'll remove the `atom-` prefix on plugins repo too)
