### ISSUE TITLE
Updating to 4.2.0 fails

### ISSUE THREAD

**Issue by serkandurusoy** [atom-minimap/minimap#272]
Fired up atom, bottom right corner showed up that there is one update (minimap 4.2.0) and I clicked upate only to get the following:

```
Updating to “minimap@4.2.0” failed.Hide output…

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open '/home/serkandurusoy/.atom/packages/minimap/node_modules/atom-space-pen-views/lib/select-list-view.js'
```

After a restart of atom, the update just disappeared!

My versions are:

```
$ atom -version
0.179.0
$ apm -version
apm  0.137.0
npm  2.3.0
node 0.10.35
python 2.7.6
git 1.9.1
```

**Comment by abe33** [comment]
Not sure what happened, does updating with `apm update` gives the same result?

**Comment by serkandurusoy** [comment]
apm update gives no error but now shows that there is another upgrade to 4.2.2 which got completed without a problem.

**Comment by zhevron** [comment]
Confirmed happening when updating from pre-4.2.0 to 4.2.2 as well. The update fails with the same message, then breaks the entire package install.

Running `apm update` doesn't fix it either, since no updates are available. I had to do `apm install minimap` to fix it and it seems to work fine now.
```
$ atom -version
0.179.0
```
```
$ apm -version
apm  0.137.0
npm  2.3.0
node 0.10.35
python 2.7.6
git 1.9.3
```

**Comment by abe33** [comment]
@zhevron I just made an update from 4.1.4 -> 4.2.2 on my work computer and I didn't get any error, do you recall which version you had prior to the update?

**Comment by zhevron** [comment]
@abe33 I was running 4.1.4 before I updated. A bit odd since I haven't been able to reproduce after that initial attempt from inside Atom. It seemed to happen during an `rmdir` call, so it could actually be something with `apm` itself and not the package.

**Comment by fundon** [comment]
I didn't get them when updating, too.

**Comment by fundon** [comment]
If you have same issue, please reopen it. Thanks.
