### ISSUE TITLE
Minimap keeps polling the dom even if pane not active

### ISSUE THREAD

**Issue by wmertens** [atom-minimap/minimap#284]
I recorded a timeline in the chrome dev tools and a minimap timer keeps polling every 100ms. It would be great if the interval timer were stopped when the pane isn't active.

This is the timer: https://github.com/atom-minimap/minimap/blob/20bad55e0b1cf226f693b2bb80a94e5f0f319b9e/lib/minimap-element.coffee#L74

**Comment by abe33** [comment]
I'm not sure what you mean by active pane, so I'll assume you talk about the focused text edtor and its parent panel. 
This timer is needed to catch resize and visibility changes of the minimap element as there's no native way of doing so. And even inactive panes can be resized so we can't simply ignore them. 
We can still avoid to process the repaint for hidden minimap. In fact this is what we already do. But to track the visibility of an element, which can be changed by CSS without any event available on the JS side, we need to poll the DOM as well. 

This is based on what [core components](https://github.com/atom/atom/blob/master/src/text-editor-component.coffee#L549-L563) already do to detect resizes and update themselves.
Recently was introduced the [`atom.views.pollDocument` method](https://github.com/atom/atom/blob/master/src/view-registry.coffee#L174-L179) for core components, the next minimap version will also start using it to avoid piling up running intervals but we won't be able to avoid polling the DOM to detect visibility and size changes.

**Comment by wmertens** [comment]
Sounds about right... This is a sad situation, it causes a constant battery
drain when the app is running. I hope there will be a better solution
available at some point. Thanks for your explanation!
