### ISSUE TITLE
Highlight "find/replace" matches in minimap

### ISSUE THREAD

**Issue by brendanfalkowski** [atom-minimap/minimap#287]
It would be nice if the mini-map showed "find/replace" candidates so you could get a sense where things are used.

Sublime Text does this, but the highlighting isn't prominent enough IMO. Example:

![sublime-text-find-minimap](https://cloud.githubusercontent.com/assets/214924/6449961/9e8cfb58-c0f2-11e4-91c0-4a00c83020e5.png)

**Comment by abe33** [comment]
Have you take a look at minimap plugins? There is one for that: 

https://github.com/atom-minimap/minimap-find-and-replace

**Comment by brendanfalkowski** [comment]
Oh, cool. Didn't know the plugins existed. Thanks!

I went straight from the minimap settings to searching the repo's issues. Hopefully other people will spot this then.

**Comment by abe33** [comment]
They are also listed at the bottom of the project README, but they probably deserve a higher position, though.

**Comment by thegrims** [comment]
There is also this [https://atom.io/packages/minimap-highlight-selected](url)
