### ISSUE TITLE
hold left mouse button for seek-then-scroll

### ISSUE THREAD

**Issue by ChaoticMind** [atom-minimap/minimap#290]
One can currently:

1. Seek/scroll to a certain location by left clicking once on the minimap (ie where the "scroll animation" option applies)
2. Click the current location on the minimap and drag up/down for a vertical scroll.

Is it possible to left click to seek (behavior 1) and keep the left mouse button held and drag to scroll (behavior 2) in one movement? 

Currently, one has to click once to navigate to a destination, then has to release and click again (and drag) to scroll. 

This is useful to scroll roughly to the target area and then adjust in one go.

**Comment by abe33** [comment]
Sadly this is not as simple as it sounds, when the minimap can scroll if you click on the minimap it'll change the change the scroll of the minimap and the position of the visible area element (which triggers drag gesture), so if we start a drag gesture at this point, the scroll will immediatley adjust to the position of the mouse which will not be the same as the visible area.

I've though about that for some time now and I haven't found a solution that satisfies me yet. We could allow this kind of gesture only if the minimap can't scroll, but it wouldn't be really consistent, as as soon as there will one line that can't be displayed in the minimap the click-then-drag gesture would no longer be available.
The other solution would be to make a click on the minimap behave in the same manner that the drag gesture, but it'll break the fact that when you click on the minimap it scrolls to make the line you clicked visible.

**Comment by ChaoticMind** [comment]
I was actually initially confused by your post because I hadn't seen the scroll behavior of the minimap yet. (I just installed it and only had small relatively short files open). This definitely makes it more complicated. 

Personally, I like the second solution (make the click behave the same way as the drag gesture) even taken on its own, unrelated to this issue.
What do you think of making that behavior into an option anyway? I see myself using the click-to-scroll behavior on the minimap as an alternative to middle-clicking atom's scrollbar (this is how sublime2's minimap behaves by default iirc).

If this option existed and is enabled, then one could imagine also hiding atom's native vertical scrollbar (at least when the minimap-scroll-indicator is also enabled), and the original feature suggested in this issue can also be enabled in that case as well. 

Maybe a separate issue should be created about that.

**Comment by ChaoticMind** [comment]
Or actually, how about this? 
Middle clicking on the minimap would behave like middle clicking on atom's native scrollbar (this is normal behavior common to scrollbars everywhere and is pretty intuitive).

That way, minimap won't have to have yet another option and would cover both cases. Left click would still scroll to make the line you clicked visible, but middle click would scroll similarily to the current click-and-drag scroll. 

Then the initial feature can be implemented iff the user middle clicked (and held).

**Comment by abe33** [comment]
Sorry for the late reply.

I reopened ST3 to compare with our current implementation and I think we're pretty close of what it's done in ST. Clicking on the minimap scrolls to make the clicked line visible, but doesn't allow to start a drag after that. Dragging the visible area works pretty much in the same way. So I don't think there's a need to change that behavior now.

However, I think that your second proposition is interesting, namely having the middle click starting a drag gesture. Are you interested in making this change yourself in a PR? You can take the drag tests as reference for the middleclick test (https://github.com/atom-minimap/minimap/blob/master/spec/minimap-element-spec.coffee#L319-L346)

**Comment by ChaoticMind** [comment]
Yeah, i'll give it a shot! I have limited js experience and none in coffeescript (nor in atom's API), so it might have a little bit of a learning curve, but i'll give it a go over the weekend. 

Thanks for the reference link. I expect most of the components are already present in one way or another in minimap, so this should be a good starter project.

I'll post here if I need some guidance.
