### ISSUE TITLE
Appended extra lines in the bottom of Minimap

### ISSUE THREAD

**Issue by fundon** [atom-minimap/minimap#292]
![issue](https://cloud.githubusercontent.com/assets/27926/6525633/c232193c-c442-11e4-9d91-765a71d0d6f7.gif)

I try to fix this.
Comment these lines: https://github.com/atom-minimap/minimap/blob/master/lib/mixins/canvas-drawer.coffee#L430-L435
And it isn't reproduce.

**Note**: Just only `READMe.md` file can reproduce it.

**Comment by abe33** [comment]
If you're able to write a test that trigger that behavior so that we can make sure that the fix you're proposing works as expected without breaking anything it'ld be great.

**Comment by fundon** [comment]
I will add a test in few days.

**Comment by fundon** [comment]
@abe33 
Atom will enable `Soft Wrap` automagically when first openning `Markdown Preview`, and it will be reproduced.
BTW, as long as enable `Soft Wrap` that  will be reproduced.

**Comment by abe33** [comment]
As far as I can tell from your gif, the soft wrap is already enabled. But my guess is that you haven't a preferred line length defined.

**Comment by fundon** [comment]
It defatuls to `80`. Not need.

**Comment by fundon** [comment]
Maybe we can use `TextEditor#isSoftWrapped` to check the status.

**Comment by abe33** [comment]
I'm not sure to understand what you're talking about. In the gif you posted, the soft wrap is already enabled before splitting the pane, so testing `isSoftWrapped` will return `true` at both times.
Also we relies on the text editor screen lines so there's should be no need for us to deal with soft wrapped lines in a special way.

**Comment by fundon** [comment]
It's working for me when commet these linnes https://github.com/atom-minimap/minimap/blob/master/lib/mixins/canvas-drawer.coffee#L440-L445.

But I'm not clear. 
I'm closing this issue. If someone has same issue, reopen it.
:)

**Comment by abe33** [comment]
I'm not saying there is no issue, your gif is telling enough, but I'm cautious with untested changes like 'comment these lines and it works'. 
We need tests that reproduce this issue so that we can make sure the fix really solves the issue without introducing new bugs elsewhere.

**Comment by abe33** [comment]
So I somehow figured what the cause was, it also seems I found a fix for that so I reopen this issue to keep track of the changes.
