### ISSUE TITLE
Preview only show the current X lines of a file

### ISSUE THREAD

**Issue by sgoguen** [atom-minimap/minimap#296]
I was expecting the preview to behave like Sublime's code map window that shows all the code and overlays the visible segment with a transparent layer.  In the screenshot below, you'll see it's only showing a small portion of a 2813 line file.

![image](https://cloud.githubusercontent.com/assets/60516/6618300/2a8077a0-c898-11e4-85ad-faba6995f15e.png)

**Comment by abe33** [comment]
Can you please tell us your version of Atom and of the minimap package?

**Comment by sgoguen** [comment]
Nevermind then!  Upgrading Atom fixed the issue.  :)

Atom: 0.168.0
Minimap: 4.6.0

**Comment by abe33** [comment]
Ok, that's good to hear. 
Latest versions only support Atom >= 0.184 but unfortunately there an issue with the `settings-view` which allow to install incompatible version of a package (see atom/settings-view#377 for details about the issue).

I'm closing this issue then.
