### ISSUE TITLE
Dragging the Minimap scrollbar above or below the Minimap Ends Scrolling the Page

### ISSUE THREAD

**Issue by sheparddw** [atom-minimap/minimap#306]
When clicking and dragging the minimap view above or below the minimap bar, scrolling stops on the page. This is annoying as I often move the cursor too high or low when trying to get to the top or bottom of the page quickly. When moving too high or too low, the minimap should scroll the page to the top or bottom respectively and resume scrolling if the user does not let go of the click and proceeds to move the cursor down or up. This is the expected behavior and is how it works in Sublime's built in minimap.

**Comment by fundon** [comment]
Thanks for your feedback.
I tried and the behavior is different from Sublime's.

I think it needs improvement.

**Comment by abe33** [comment]
Fixed in 4.7.1
