### ISSUE TITLE
Minimap Erases when Overflowing

### ISSUE THREAD

**Issue by Charlesetc** [atom-minimap/minimap#309]
So when you have a document is so long that the minimap is larger than the size of the window, the "text" on the minimap disappears when you scroll to the top. This means that when you scroll back to the bottom, there is no data on the minimap for the end of the page. 

Here's an example:

![Example](https://cloud.githubusercontent.com/assets/5167293/6991386/93808630-da56-11e4-9da7-a145cb76b5ad.png)

**Comment by fundon** [comment]
Hi @Charlesetc, sorry for the later reply.

Is the latest Atom and Minimap?

**Comment by Charlesetc** [comment]
Hi @fundon, 
Here's are the versions. I think everything's up to date.

~$ apm --version
apm  0.157.0
npm  2.5.1
node 0.10.35
python 2.7.6
git 1.9.3
~$ atom --version
0.189.0
~$ apm list | grep minimap
├── minimap@4.7.5

Let me know if there's anything else I can do.

**Comment by fundon** [comment]
How many lines or size of your file?

**Comment by Charlesetc** [comment]
300 lines will do it

**Comment by abe33** [comment]
Hmm, there must be something else, long files were obviously a case that was considered in the design of the minimap.
You can see what I get on my configuration, first with manual scroll, then using jump to top/bottom commands: 

![minimap-scroll](https://cloud.githubusercontent.com/assets/247140/7003459/fc399ecc-dc5a-11e4-820e-6bb05f1fac3f.gif)

We'll need you to investigate a bit what's going on.
Is it something that occurs systematically when the file is longer than the minimap capacity?
Have you errors or warnings in the devtools? 
Does the *hole* stays if you resize the window a bit? (resize triggers a full re-render of the minimap, while scrolling use an offscreen canvas to reduce render time)

**Comment by abe33** [comment]
BTW @fundon I was considering changing the default value for char height. 1px is much closer to ST than the current 2px, and the performances are pretty good even on really large screens (at work I'm pretty much fullscreen on a 27" cinema display). What do you think about it?

**Comment by fundon** [comment]
Maby the 1px is too smaller, but these are more performances, we can chang that.
And if anyone does not like this changing, (s)he can customize it by (s)heself.

**Comment by Charlesetc** [comment]
Resizing the window fills in the minimap. There aren't any errors in the dev console. And yeah, it happens in every file sufficiently long.

**Comment by almostearthling** [comment]
Hi, maybe this behaviour can fit in the same bug: if not, please tell me and I can file a new bug report separately. I copy here some details generated by Atom's bug report tool, maybe they can be useful.

# Minimap not showing code on some tabs

The minimap does not render code in some of the tabs that were not on foreground on Atom startup.

![Minimap Behaviour](https://raw.githubusercontent.com/almostearthling/hello-world/master/images/bug_minimap.gif)

When the window is resized, or the minimap settings are tinkered with, the minimap shows again. Also, if the code can be scrolled, scrolling it causes the minimap to rendere correctly.

## Repro Steps

1. At startup, click the code tabs
2. Some of them, other than the one that was initially focused, don't show the minimap

**Expected:** Minimap showing correctly
**Actual:** Code not shown, sometimes a small dot is highlighted on the upper right corner of the minimap

## Command History

```
     -0:12.2 editor:detached (atom-text-editor.editor)
     -0:12.2 editor:will-be-removed (atom-text-editor.editor)
     -0:12.2 pane:item-removed (atom-pane.pane.active)
     -0:12.2 editor:detached (atom-text-editor.editor)
     -0:12.2 editor:will-be-removed (atom-text-editor.editor)
     -0:12.2 uri-opened (atom-workspace.workspace.scrollbars-visible-always.theme-flatland-dark.theme-seti-ui)
     -0:09.0 pane-container:active-pane-item-changed (atom-pane-container.panes)
     -0:09.0 pane:active-item-changed (atom-pane.pane.active)
     -0:05.9 pane-container:active-pane-item-changed (atom-pane-container.panes)
     -0:05.9 pane:active-item-changed (atom-pane.pane.active)
     -0:00.0 bug-report:open (ul.list-inline.tab-bar.inset-panel)
```

## Versions

* **Atom:**       0.198.0
* **Atom-Shell:** 0.22.3
* **OS:**         linux 3.13.0-52-generic
* **Misc**
    * apm  0.166.0
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.6
    * git 1.9.1

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.0.</small>

**Comment by abe33** [comment]
Sorry for the late reply, do you still get that problem? Would you mind doing some tests for me so that I can grasp what's going wring here?

**Comment by almostearthling** [comment]
If that's related to the behaviour I pointed out, it just disappeared with the immediately following version of minimap.

**Comment by abe33** [comment]
@almostearthling Thanks for the feedback, and glad to hear it now works for you :)
