### ISSUE TITLE
Some tests fail (regression?)

### ISSUE THREAD

**Issue by ChaoticMind** [atom-minimap/minimap#312]
[These](https://github.com/atom-minimap/minimap/blob/v4.7.6/spec/minimap-spec.coffee#L79) [two](https://github.com/atom-minimap/minimap/blob/v4.7.6/spec/minimap-spec.coffee#L154) tests are currently failing for me.

**Comment by abe33** [comment]
Yes, I have them failing as well when running the test suite locally. I haven't found the origin yet, looks like there's some significant differences between running tests in a local Atom installation and tests on Travis. Don't mind them for the moment, at least we know that they're expected to fail locally.

**Comment by abe33** [comment]
\o/ Found the origin.

For the first, the introduction of batched changes in the text editor has changed the change object we receive so the tests weren't accurate anymore.

For the two other tests, it seems that now a `TextEditor` without a view can't scroll horizontally except by mocking the `displayBuffer.getScrollWidth` method. It's much more hacky than for the first failure, I'll take some time later to see how making it work properly.
