### ISSUE TITLE
Bad behavior with "autocomplete" box

### ISSUE THREAD

**Issue by silverkorn** [atom-minimap/minimap#317]
Using Atom 0.190.0 with autocomplete 0.44.0 and/or autocomplete-plus 2.9.0 + minimap 4.7.6 on Windows 7 64-bits.

Combining with official `autocomplete` or third-party `autocomplete-plus`, minimap push their box in the middle:

![with-minimap](https://cloud.githubusercontent.com/assets/2325424/7090697/db2c9868-df72-11e4-9e1d-b908f2f42b17.png)

![without-minimap](https://cloud.githubusercontent.com/assets/2325424/7090720/fa46ac20-df72-11e4-97b4-63e68c2241aa.png)

**Comment by abe33** [comment]
Thanks for the report, I'll try to find a workaround so that we don't have to touch to `autocomplete-plus` but I fear that it won't be enough.

**Comment by silverkorn** [comment]
All efforts are appreciated, thanks!

**Comment by tfausak** [comment]
:+1: This affects me too.

**Comment by benogle** [comment]
This might be a problem in core. Autocomplete uses the overlay decoration for positioning, and there are lot of size calcs going on in there...

**Comment by abe33** [comment]
@benogle that was the conclusion I reached, I was planning to look at that. 
Do you know if this kind of problem was reported for another package or is minimap the only package that attaches itself in the editor like that?

**Comment by benogle** [comment]
I havent seen it anywhere else. I've added this to my autocomplete list, but might take me a bit to get to it.

**Comment by senditu** [comment]
Yeah, I'm experiencing this too :(
But I'm pretty sure this only started happening recently, which is odd.

**Comment by lexicalunit** [comment]
:+1: Seeing this too.

**Comment by mnquintana** [comment]
:+1: I've been seeing this for a long time.

**Comment by benogle** [comment]
Sorry, i'll look into this soon

**Comment by benogle** [comment]
This is definitely a core issue. I'm computing the [gutter width](https://github.com/atom/atom/blob/44db3e7d2b56cc4ca32b24d47d3964e60ff761ab/src/text-editor-presenter.coffee#L354) rather than measuring, which takes the minimap into account. Fixing now.

**Comment by benogle** [comment]
A fix has been merged, and will be out in 0.195

**Comment by fundon** [comment]
Nice!

**Comment by abe33** [comment]
Thank you @benogle! 

I'll be waiting the release of 0.195 before closing this ticket then.

**Comment by silverkorn** [comment]
Really nice to see that this module (and maybe many others) are watched by the core developers/contributors! :smiley:

**Comment by abe33** [comment]
Ok, so I'm closing as 0.195 is out for some time now.
