### ISSUE TITLE
Minimap causes text selection + scrolling to be way too fast.

### ISSUE THREAD

**Issue by SBSTP** [atom-minimap/minimap#319]
Atom v190
Minimap v4.7.6

**Comment by SBSTP** [comment]
I'm not able to reproduce it at the moment. When I disabled the plugin, it generated errors every time I selected text.

**Comment by abe33** [comment]
Hmm, have you the `minimap-selection` package installed, maybe I've omitted to unregister some stuff on minimap deactivation.

**Comment by abe33** [comment]
@SBSTP Do you have any news on that? Is it still a problem that you encounter?

**Comment by SBSTP** [comment]
I haven't been able to replicate, I think it can be closed.

**Comment by abe33** [comment]
Thanks for the feedback :)
