### ISSUE TITLE
Add "Toggle Minimap" to context menu on atom-text-editor-minimap element

### ISSUE THREAD

**Issue by mnquintana** [atom-minimap/minimap#326]
To make it a bit more intuitive to toggle Minimap with the mouse, it would be great if there were a context menu item for "Toggle Minimap" when right-clicking on the `atom-text-editor-minimap` element.

The reason this is an issue instead of a PR is because I found that for some reason using `atom-text-editor-minimap` as a selector in the menus config wasn't working.

**Comment by abe33** [comment]
Thanks for the suggestion.

How do you see that? On a per-editor basis or just as a binding to the corresponding command?

**Comment by mnquintana** [comment]
Ah that's a good point! I meant just as a binding to the existing command, but it might be more intuitive if it just toggled the Minimap on a per-editor basis – I'm not totally sure.

**Comment by abe33** [comment]
Ok, I'll probably go with just a binding to the command for the moment, as all the other controls are global ones it makes more sense like that.
