### ISSUE TITLE
hue-rotation not being applied to minimap

### ISSUE THREAD

**Issue by plttn** [atom-minimap/minimap#330]
This is a super super edge case, but my theme uses hue-rotate, and the output hue is not displayed in the minimap, but rather the original hue.

![example](https://lh3.googleusercontent.com/--4RvzQ7eMCw/VVmN1zH0VtI/AAAAAAAATx4/xIs07Z2xUXM/s0/2015-05-17_23-59-35.png)

**Comment by abe33** [comment]
Thanks for the report, 
I haven't seen this kind of issue before, did this problem is still present after a restart? 
Maybe I'm not listening to all the stylesheets/themes related events and I the styles cache isn't invalidated when you touch the theme.

**Comment by plttn** [comment]
Still occurs after restart. Theme is "tubster-syntax", repro file: https://raw.githubusercontent.com/plttn/boilerplates/master/html.html

**Comment by abe33** [comment]
Hmm I see, it's not a less color transform but a webkit filter. I'm not sure how I can retrieve the computed colors so I'll have to search documentation on that matter.
