### ISSUE TITLE
minimap extends beyond the screen, there are something wrong with display.

### ISSUE THREAD

**Issue by lisi1987** [atom-minimap/minimap#331]
Minimap extends beyond the screen, there are something wrong with display.

Atom 0.199.0

MacBook Pro (Retina, 13-inch, Late 2013)

OS X 10.10.3

**Comment by abe33** [comment]
I'll need more information: a screenshot would be great, but also the version of the minimap package and the theme you're using as it's probably related.

**Comment by lisi1987** [comment]
First, this is a normal state when I open it.

![screen shot 2015-05-20 at 10 03 02 am](https://cloud.githubusercontent.com/assets/5188604/7717684/fd2354aa-fed7-11e4-9402-5f7a616ddb80.png)

Next, I scrolled the doc and than appear this:
![screen shot 2015-05-20 at 10 03 45 am](https://cloud.githubusercontent.com/assets/5188604/7718018/3a6d95dc-fedd-11e4-9c24-e760529b7e95.png)

These are atom info:
![screen shot 2015-05-20 at 10 04 10 am](https://cloud.githubusercontent.com/assets/5188604/7717977/8a00aa2c-fedc-11e4-9e50-05bf5f2ade5d.png)
![screen shot 2015-05-20 at 10 04 53 am](https://cloud.githubusercontent.com/assets/5188604/7717978/8fbc595c-fedc-11e4-8ee3-28ba3ba201b6.png)

**Comment by abe33** [comment]
Oh, I see, I think we add this one before but I thought it was fixed as it wasn't reported. I guess I'll have to take some more time to check what goes wrong.

One more question, do you get that behavior whenever a file make the minimap scroll or does it appear random?

**Comment by lisi1987** [comment]
If minimap extends beyond the screen than will appear.

**Comment by abe33** [comment]
Sorry for the delay, I don't really get what's going on, would you be ok to do some tests for me, so that I can understand what goes wrong?

**Comment by lisi1987** [comment]
er..
It's good now ~
I don't know the reason and  don't operate anything.
