### ISSUE TITLE
Minimap Pane Highlighting Option

### ISSUE THREAD

**Issue by timothyerwin** [atom-minimap/minimap#334]
This is a feature request. Can you please add an option to set the color of the scroll highlight pane? The current one is difficult to see. I'd love to be able to set it to yellow for example.

**Comment by abe33** [comment]
Hmm, what do you call a `scroll highlight pane`? I'm not sure to see what you're referring to, do you mind showing me that on a screenshot?

**Comment by timothyerwin** [comment]
It appears on hover and you use it to slide the scroll.

**Comment by abe33** [comment]
Hmm, if you mean the visible area there's a section in the README that explain how to tweak that: https://github.com/atom-minimap/minimap#changing-the-color-of-the-minimaps-visible-area

**Comment by timothyerwin** [comment]
ain't nobody got time for that

**Comment by abe33** [comment]
Why using Atom then? 
As you say, nobody got time for that, I'm no exception.

**Comment by timothyerwin** [comment]
well you wrote the control? you have a lot of settings there and this is a basic usability issue. I'm saying the minimap scroll highlight color is barely different from the background.

I dont want to dig around styles and all that just to be able to see the contrast better.

**Comment by abe33** [comment]
We use a setting only when we don't have any other way to control something or when it has an impact on the behavior of the minimap. 
While it's true that the README would deserve more explicit examples (with screenshots for instance) I can't possibly satisfy everyone's whim. If I did there would be a setting for pretty much everything, from size to colors. As Atom is built upon web technologies most things can be customized through CSS and that's how it should be if we follow separation of concerns.
