### ISSUE TITLE
Minimap gear is partially overlapped by scrollbar when in absolute mode

### ISSUE THREAD

**Issue by GameplayJDK** [atom-minimap/minimap#345]
So, this is once again just a little graphical enhancement thingy:

The styled scrollbar of the editor pane overlaps a bit of the settings gear of the minimap, when it's in absolute mode on the right side:

![untitled](https://cloud.githubusercontent.com/assets/4069263/8161271/17cb082c-1376-11e5-92a4-ee6de3510b43.png)

This isn't too important (as I'm not using the absolute mode anyways) :)

**Comment by abe33** [comment]
Oh nice catch, as OSX scrollbars aren't visible unless you scroll above them I didn't notice that problem :).
