### ISSUE TITLE
Performance after recent Atom upgrade

### ISSUE THREAD

**Issue by Instagit** [atom-minimap/minimap#346]
After upgrading Atom from 0.195.0 to 0.210.0 on 64-bit Ubuntu, minimap makes Atom unusably slow. Scrolling, selecting text, even typing, everything is affected.

With minimap disabled, CPU usage is evenly distributed between **atom --type=gpu-process** and **atom --type=renderer**. With minimap enabled, **atom --type=renderer** does almost all the work.

CPU is an i7 and GPU a GTX 560 Ti with proprietary Nvidia drivers 331.113.

**Comment by abe33** [comment]
Have you tried profiling Atom from the devtools when minimap is activated? (using both the timeline and javascript profiling tools)
I haven't noticed performances drop in latest versions so I would like to understand what's slowing down Atom in your case.

Also, what's your config? Have you activated hardware acceleration in the minimap settings? Do you use absolute mode? etc.. 
Having your whole minimap config can help understand what could go wrong.

**Comment by Instagit** [comment]
Here's my config.cson:

````
"*":
  core:
    themes: [
      "atom-dark-ui"
      "monokai"
    ]
    audioBeep: false
    disabledPackages: [
      "minimap"
      "minimap-git-diff"
      "minimap-selection"
    ]
  "exception-reporting":
    userId: "1234567890"
  welcome:
    showOnStartup: false
  metrics:
    userId: "1234567890"
  editor:
    fontFamily: "Droid Sans Mono"
    fontSize: 15
    invisibles: {}
    softWrap: true
  minimap:
    plugins:
      selection: true
      "git-diff": true
    textOpacity: 0.3
    charHeight: 1
    charWidth: 0.5
  "tree-view":
    showOnRightSide: true
  whitespace:
    ignoreWhitespaceOnCurrentLine: false
  "atom-beautify":
    _analyticsUserId: "1234567890"
    analytics: false
  "markdown-preview": {}
  emmet: {}
````

**Comment by Instagit** [comment]
And profiler results for three different configurations:
![minimap-overview](https://cloud.githubusercontent.com/assets/2681794/8250221/f163ecb8-1671-11e5-8a24-761bd5ada0b1.png)

**Comment by abe33** [comment]
Thanks for the feedback, I could reproduce that myself thanks to your explanations. It mostly looks like an issue with the selection plugin which remove/recreate a decoration each time the selection change, causing a lot of repaints. Not sure how I can fix that, but I'll try a few things during this week-end.

**Comment by saschagehlich** [comment]
I'm experiencing this issue lately with larger files as well. Whenever I type something, the minimaps start to flicker.

**Comment by abe33** [comment]
@saschagehlich and have you tried to profile Atom to define where's the bottleneck is?

**Comment by erwinverdonk** [comment]
This appears to be solved in v4.13.3

**Comment by Instagit** [comment]
Agreed, the performance is a lot better now. Thanks for the updates.

The minimap-selection package still causes a noticable performance hit, but I'd close this issue here if there are no more complaints.

**Comment by abe33** [comment]
@Instagit Thanks for the follow up
