### ISSUE TITLE
Show selected text / current line

### ISSUE THREAD

**Issue by DepthDeluxe** [atom-minimap/minimap#348]
It would be nice to have the minimap highlight text that the user has selected.  In addition, it may also be cool to have the user's current line highlighted.  Thoughts?

**Comment by abe33** [comment]
The selection can be actually displayed using the [`minimap-selection`](http://atom.io/packages/minimap-selection) plugin.
It shouldn't too hard to adapt it to highlights the lines with cursors even when there's no selection. I'll look about that.

**Comment by abe33** [comment]
I'll close that issue, and I'll open one on the `minimap-selection` plugin instead.
