### ISSUE TITLE
i installed the minimap package and it didn't show up  

### ISSUE THREAD

**Issue by mmzizo** [atom-minimap/minimap#349]

**Comment by abe33** [comment]
And you does not have any errors notified or messages in the devtools console?

**Comment by manV** [comment]
Same thing happened to me, uninstall and enable buttons stays greyed out and console show that

"Could not resolve 'minimap' to a package path" on line chrome-devtools://devtools/usr/share/atom/resources/app.asar/src/package-manager.js:377

I am using atom 1.0.0 on ubuntu 14.10

**Comment by abe33** [comment]
Have you tried to install it again? The atom website was quite busy yesterday due to the 1.0 release.

**Comment by mmzizo** [comment]
/home/mahmoud/Pictures/error.png

**Comment by mmzizo** [comment]
​

**Comment by manV** [comment]
Reinstalled and now its working, thank you @abe33 for awesome package.

**Comment by abe33** [comment]
Glad to hear that, I'll close the issue soon except if @mmzizo has more information to provide.
