### ISSUE TITLE
Enable/Uninstall problem

### ISSUE THREAD

**Issue by wwmyers** [atom-minimap/minimap#352]
I've decided I didn't want minimap on Atom and disabled it. I've done many updates since then, but now when I try to either enable or uninstall, it does nothing. I've even tried uninstalling it in the terminal by using atm. Task completed successfully, but it still shows up under my Atom packages, but with a yellow mark instead of a green mark. It's also greyed out. Any ideas?

**Comment by abe33** [comment]
And there's no error in the console when you try to enable it again?
Also, have you tried removing it manually from the disabled package field in your `config.json` file?

**Comment by wwmyers** [comment]
abe33 Thanks!, deleting from config worked perfectly.
