### ISSUE TITLE
Minimap messes up editor size in fullscreen mode

### ISSUE THREAD

**Issue by samuela** [atom-minimap/minimap#354]
Ref: https://github.com/atom/atom/issues/7604. I'm certain that minimap is the culprit; disabling it fixes the issue.

**Comment by abe33** [comment]
Hmm, I can't confirm that on my computer (OSX 10.10.4) with the one-dark-ui theme. I'll need you to gives me more details about your config, the theme you use, the other package installed, etc.

**Comment by samuela** [comment]
Hmm, I'm not able to reproduce it now either. I did just update it though. I guess I'll reopen if I come across it again.

**Comment by abe33** [comment]
Ok, thanks for the feedback!
