### ISSUE TITLE
Can't drag minimap-visible-area when jumping

### ISSUE THREAD

**Issue by yishn** [atom-minimap/minimap#356]
If you click outside the minimap-visible-area, it will jump to your mouse position. But unless you let go of your mouse button, you can't drag the minimap-visible-area around. It would be nice if this was possible, as you can fine-adjust where you want to jump.

**Comment by abe33** [comment]
It was already reported in #290 if you want to see my initial answer on this matter. Turns out @ChaoticMind implemented something like that on the middle click in https://github.com/atom-minimap/minimap/pull/304. 
Maybe we should add a binding for another event that middle clicks.
