### ISSUE TITLE
Minimap / Split View issue

### ISSUE THREAD

**Issue by rm-code** [atom-minimap/minimap#358]
Hello,

I wasn't sure wether to report this bug here or in the [markdown-preview](https://github.com/atom/markdown-preview) repository. When the minimap is on the right and I toggle the markdown preview, the minimap is automatically transferred to the left side of the screen.

![screenshot 2015-07-04 10 08 13](https://cloud.githubusercontent.com/assets/11627131/8507121/c232e3bc-2234-11e5-9159-0e939968bcc8.png)

(Had to toggle the tree-view to make the minimap options visible. As you can see it still thinks it is on the right side of the screen and the option panel is displayed offscreen)
![screenshot 2015-07-04 10 08 50](https://cloud.githubusercontent.com/assets/11627131/8507122/c51051c8-2234-11e5-8767-75169dc76d60.png)

When I untoggle the markdown preview, the minimap is not restored to its original place. 
![screenshot 2015-07-04 10 09 01](https://cloud.githubusercontent.com/assets/11627131/8507128/faaba350-2234-11e5-9d9b-c5b7291d22c5.png)

Best wishes
Robert

**Comment by abe33** [comment]
Interesting, I never seen that happens (I also use Markdown Preview a lot), it looks like the minimap position setting was not changed in the process, can you confirm it? The value for `minimap.displayMinimapOnLeft`should be false. 
If not then some code has changed the setting in the process, but I have no clue why it happens. 
If yes, then maybe there's some CSS issue at some point, the minimap make use of the flex box display used by the text editor, but the order of the elements in the layout can be changed directly from CSS, can you inspect the minimap to see if there's a `flex-order` that applies at some point on the minimap or on the text editor?

**Comment by rm-code** [comment]
In the config file the value for minimap.displayMinimapOnLeft is omitted (so I guess it defaults to 'false').

I couldn't find a ```flex-order``` on inspection, but I am not too familiar with the inspection tool and the CSS / styling code.

**Comment by abe33** [comment]
Can you tell me what is the position of the `atom-text-editor-minimap` element in the DOM before and after the side switch? Maybe it detaches and attaches itself at the wrong place (which would be weird, but I don't see any other reason for that behavior)

**Comment by rm-code** [comment]
But I noticed something different. It doesn't just happen with the markdown preview, it also happens when I split the view myself. I hope this helps:

![screenshot 2015-07-09 11 38 24](https://cloud.githubusercontent.com/assets/11627131/8592390/405c9eec-262f-11e5-8939-7f5d5696db8f.png)
![screenshot 2015-07-09 11 39 37](https://cloud.githubusercontent.com/assets/11627131/8592392/427f9030-262f-11e5-8f23-255ddc05f3a7.png)

**Comment by abe33** [comment]
This is really weird, the minimap is inserted at the wrong place, but I can't figure why nobody else has reported the same behavior.
If the setting doesn't change there's no reason for the minimap to be inserted elsewhere than at the end of the children list.
What's even weirder is that the second minimap on a pane split is positionned at the right place. So it can't be that the config changed.

If you can try something in the console for me when it occurs: 

```js
e = atom.workspace.getActiveTextEditor()
minimap = atom.packages.getLoadedPackage('minimap').mainModule
m = minimap.minimapForEditor(e)
v = atom.views.getView(m)
v.displayMinimapOnLeft
``` 
The last line should return false if the minimap is in sync with the config, if it's true then that explain why the minimap swapped place, but the question would then be why this value was changed in the process. 
If it's still false then I don't understand what could produce that.

When I test that myself with some debug code in the attach and detach hooks of the minimap element, I only get one attach call when I split a pane, which should indicate that the element is not removed from the text editor.

By curiosity, do you get the same result with `displayMinimapOnLeft` enabled? Does the minimap swap to the right on a split pane or does it stay on the left?

If it don't change position it could indicate than the content of the text editor is destroyed and then recreated after the minimap. But you'll be the only person I know that experience that when splitting panes.

**Comment by rm-code** [comment]
> By curiosity, do you get the same result with displayMinimapOnLeft enabled? Does the minimap swap to the right on a split pane or does it stay on the left?

Just tested it: If I use the "Left" option both views will have the minimap on the left side. This seems to be a problem exclusively with the "right" position.

> The last line should return false if the minimap is in sync with the config, if it's true then that explain why the minimap swapped place, but the question would then be why this value was changed in the process. 
If it's still false then I don't understand what could produce that.

It returns ```false``` here :( 

Not sure if this is relevant, but the wrongly placed minimap will only update it's position after I actually put it on the side it is on ... Let me try to explain it a bit better:

1. Minimap is on the right
2. Split Panes
3. Minimap is now on the left (but the minimap option still shows "Right)
4. When I click on the "right" option now, I get no reaction
5. When I click on the left option nothing happens either (since the minimap is already on the left)
6. Now clicking on "right" updates the position correctly

**Comment by abe33** [comment]
I believe the patch in v4.11.2 should solve this issue, the minimap no longer rely on the node position for the layout, but instead it uses the `order` property of flexbox content to appear before the editor. So whatever the order is the layout should always be the same. Let me know if you still have an issue with this.

**Comment by rm-code** [comment]
Just downloaded 4.11.2 and everything works as expected! Cool, that you found a fix for this :+1:
