### ISSUE TITLE
minimap blur

### ISSUE THREAD

**Issue by axoquen** [atom-minimap/minimap#361]
When i use mousewhel scrolling the canvas element take a blur 
check the height condition...
(sorry for my bad inglish)

![test15](https://cloud.githubusercontent.com/assets/1342224/8680476/40dcb568-2a27-11e5-84b9-34a68ec444a4.gif)

**Comment by abe33** [comment]
It looks like a windows specific issue, not sure I have a solution right now, I'll try to think of something for you to try if you don't mind (I don't have a window at hand to test things by myself).

**Comment by abe33** [comment]
BTW, are you using a float value in the minimap settings?

**Comment by axoquen** [comment]
yeah, in the "char height" field....  my fault... thank you 

excelent package

**Comment by abe33** [comment]
No, no, it's not really your fault, it's just that I haven't really anticipated this case despite knowing it would come, so I knew that it would probably cause something like that. The thing is that with float values chrome start to apply antialias, and as we copy an offscreeen bitmap it apply the antialias over and over and you get that increasing blur effect. 
But just rounding the values doesn't give a great result, and reimplementing canvas antialiasing is clearly out of the scope, so we just have to deal with that for the moment.

**Comment by abe33** [comment]
As for the config:  The closer render from ST I can get is by using 1px char height/0px line space, but to be closer we should render each char separately to introduce antialias at the char level for a 1px/2px chars (no need to say it's an overkill). Actually I use 1px char height/1px line space as my current setup quite close to ST but with less burden on the drawing routine (the thinner the rows, the more rows you have to draw).
