### ISSUE TITLE
Can't really use the minimap with a touchscreen

### ISSUE THREAD

**Issue by AlexanderLJ** [atom-minimap/minimap#362]
The minimap does respond, but only lets you click outside of the indicator. You can't move the indicator up or down using your finger. 

(Although right now Atom overall doesn't work nicely on a tablet like ST2 does, with the onscreen keyboard popping up all the time. not being able to select text with your finger and so on. Although this isn't a atom-minimap related issue)

**Comment by abe33** [comment]
Thanks for bringing that up, It shouldn't be a problem to fix that in the minimap.
