### ISSUE TITLE
Text overflows behind minimap - can't be seen even after scrolling

### ISSUE THREAD

**Issue by stebiger** [atom-minimap/minimap#366]
When typing long lines the text overflows behind the minimap.
You can't scroll horizontal as the minimap overlaps the text and you can not see everything then.

Regards,
Stefan

**Comment by abe33** [comment]
That's only if you use the absolute mode, if you don't want the text to flow below the minimap you can just turn this setting off.

**Comment by stebiger** [comment]
Hey,

thanks for replying - I even discoverd this is a nort a problem of minimap but of the apathy syntax theme I was using.
Sorry!

**Comment by abe33** [comment]
Oh interesting, did you inspect the text editor & minimap? I'll be curious to know why it failed, my guess is that it's probably related to the use of flexbox for the layout.

**Comment by stebiger** [comment]
Not yet - I just opened an issue on the apathy theme https://github.com/coopermaruyama/apathy-theme/issues/17
