### ISSUE TITLE
Show added / modified / deleted indication on minimap

### ISSUE THREAD

**Issue by azoerb** [atom-minimap/minimap#369]
Along the left side of the editor, there are green, yellow, and red indicators for where lines have been added, modified, and removed respectively.
![Imgur](http://i.imgur.com/bC4HUm2.png)
It would be nice to be able to somehow see these indicators on the minimap.

Perhaps the entire added / modified line in the minimap could be highlighted with green / yellow, and a thin red line across the minimap could indicate removed lines.

This would be helpful for getting a quick overview of all current change in the file without having to scroll through the entire thing.

**Comment by abe33** [comment]
See [minimap-git-diff](http://atom.io/packages/minimap-git-diff) ;)
