### ISSUE TITLE
Minimap overlaps the lines in the editor

### ISSUE THREAD

**Issue by yriveiro** [atom-minimap/minimap#370]
Minimap overlaps the lines of the editor.

![screenshot 2015-07-30 10 17 03](https://cloud.githubusercontent.com/assets/934763/8979872/a3b559ae-36a4-11e5-98ea-7b9d30f45296.png)

Atom: 1.0.3
Minimap: 4.12.1

**Comment by abe33** [comment]
Have you enabled the `absolute mode` setting?

**Comment by yriveiro** [comment]
Yep

![screenshot 2015-07-30 14 13 00](https://cloud.githubusercontent.com/assets/934763/8983806/1ccead02-36c5-11e5-9dca-7a7bf525cbd8.png)

**Comment by abe33** [comment]
Then disable it ;).

**Comment by yriveiro** [comment]
I don't remember change this setting ... either way it works :D
