### ISSUE TITLE
Extract out Plugin Generators for JS and ES6 ? 

### ISSUE THREAD

**Issue by ganarajpr** [atom-minimap/minimap#377]
I am extremely new to atom plugin development - so let me know if I am assuming too much here.

I have been looking at various other discussions where people have been looking for ES6 or JS package generators. The package generator that I see here as part of minimap is actually pretty awesome and helps people get on board quite easily. 

If my understanding is right, couldnt these be extracted out and provided as a generic package generator es6 and package generator js for example - so that it serves a more broader audience ?

**Comment by abe33** [comment]
Except for the minimap-specific parts, yes, the main stuff is here.

**Comment by revolunet** [comment]
do you know any atom es6 plugin boilerplate ?

**Comment by ganarajpr** [comment]
I created one here based on the one in minimap

https://github.com/ganarajpr/atom-package-babel-react-boilerplate

**Comment by revolunet** [comment]
you are wonderful, thank you :heart:
