### ISSUE TITLE
Updating to “minimap@4.13.2” failed.

### ISSUE THREAD

**Issue by doreto** [atom-minimap/minimap#382]
npm ERR! tar.unpack error reading C:\Users\User\.atom\.apm\d\0.1.1\package.tgz
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\User\\AppData\\Local\\atom\\app-1.0.7\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\User\\AppData\\Local\\atom\\app-1.0.7\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\User\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\User\\.atom\\.apmrc" "install" "C:\\Users\\User\\AppData\\Local\\Temp\\d-11583-304-18xep0q\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code EBADF
npm ERR! errno 9

npm ERR! EBADF, fstat
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by abe33** [comment]
Looks like an issue with apm. Have you tried installing it again?

**Comment by doreto** [comment]
I did reopen Atom editor and fixed the problem.
