### ISSUE TITLE
Touch events unsupported

### ISSUE THREAD

**Issue by WhyEvenTry** [atom-minimap/minimap#383]
The minimap does not react to any touch events, not a simple touch (=click), not touch-scroll (=mouse scroll).

Yes yes "pull requests welcome" - I'm completely new to Atom and I'm still struggling with very basic things, this seems extremely simple to add for anyone with even a mild background in how to write code for Atom...

Especially on touch screen ultrabooks being able to use the minimap to scroll and jump quickly to any section of a file is a huge usability plus. It's how I got WebStorm to be usable for me - they have a minimap add-on too and fortunately it works with touch and touch-scroll, making that editor _much_ more usable on an ultrabook.

**Comment by TimeForAChange** [comment]
After some more tests: having the touch-event package active leads to touch events not registering in the minimap module. But that module is essential to be able to work with a touch screen at all - without it I get a Windows on screen keyboard each and every time I touch the screen. And yes, the OSK is *disabled* in Windows (10), I even checked the registry key for the OSK. Atom is the only application that manages to trigger it.

But even when I disable the touch-event package, only simple touch = click works, moving (dragging/scrolling) is not possible.

**Comment by abe33** [comment]
Hi @TimeForAChange, thanks for the report. Actually I don't have access to this kind of device so all the work I've done on that is based on the touch events specifications so I can't really guarantee that it works. If someone is willing to help me with that it would be great, as there's little chance that I can access such device in a near future.
