### ISSUE TITLE
Extreme input lag at top of long HTML file, with code-highlights disabled.

### ISSUE THREAD

**Issue by JesseLeite** [atom-minimap/minimap#384]
I'm noticing extreme input lag, but only in very specific situations.  For example:

- Long HTML file
- Editing text near top of file
- Minimap enabled
- Minimap's code-highlighting disabled

I used package-cop to narrow it down to this.  What could be happening with the rendering of the minimap without code-highlights, which might cause this?

Here's an example screencast, but even at 60fps it's very hard to see.  Very easy to feel though, and should be easy to reproduce if you follow my exact steps above.  With input lag, sometimes it spits out 2 or 3 characters at a time while it's trying to catch up.  Without the input lag, each character displays as fast I'd expect in --safe mode.

![minimap-input-lag3](https://cloud.githubusercontent.com/assets/5187394/9687508/dae94eb6-52f7-11e5-89d5-aba083ae5454.gif)

Seems like such an obscure issue… but it’s very noticeable when it happens.  I can just enable code-highlights to avoid it, but I prefer code-highlights disabled so that I can better see minimap's git-diff colouring.

**Comment by abe33** [comment]
Thanks for the report, I never noticed this issue but I don't really use minimap without code highlighting so I'll have to profile what's going on here.

**Comment by JesseLeite** [comment]
Were you able to reproduce the lag on your end?

**Comment by abe33** [comment]
Yes I can reproduce it, by profiling I could narrow down the issue to the routine that read the colors from the DOM, it looks like it fall in a case where the cache isn't properly used. I think it should be pretty easy to fix. Stay tuned.

**Comment by JesseLeite** [comment]
Awesome, thank your for your time.

**Comment by JesseLeite** [comment]
It's fast now, thank you!  Just one param in that git diff :) ...was it difficult to find the cause?

**Comment by abe33** [comment]
Nope, profiling always help in that kind of context. Once I know where there's a bottleneck I just put some logs to see why the cache was never used and found I was forcing to not use the cache in that case, which was no longer needed (I don't really remember why I did this but it probably dates from a time when I didn't listen to stylesheets additions and had to prevent the cache to store a text color from before the themes loading).

**Comment by JesseLeite** [comment]
Interesting.  Well thanks for the fix man.  Have a great day!
