### ISSUE TITLE
Stucks when long-clicking somewhere to scroll

### ISSUE THREAD

**Issue by rugk** [atom-minimap/minimap#385]
It's difficult to describe, so I think this gif explains it much better:
![minimapscrollto](https://cloud.githubusercontent.com/assets/11966684/9857473/0712fb24-5b1b-11e5-9992-c1a35744536f.gif)

Minimap shouldn't stuck there but just scroll up/down as long as I click.

I've set the scroll animation delay to 150, but it's the same result with the default one.

**Comment by abe33** [comment]
Hi there, the minimap behavior is based on the Sublime Text one (as most new Atom are probably accustomed with it), and this is how it behaves. When clicking in the minimap it scrolls the editor to reach the line below the mouse at the moment of the click but won't continue to scroll after that.

**Comment by rugk** [comment]
Mhh, okay. In this case what about an option so you can change this behaviour?

Actually you can already do this by setting the scroll delay to 0. Because the 'slider' is cached very fast it's recognized as a drag/drop operation.
However you of course loose the animation with this method.

**Comment by ChaoticMind** [comment]
If your goal is not [just] to scroll in that direction until mouseup, but to ultimately keep scrolling until the minimap reaches your cursor's position, then try middle-clicking (also no animation)

**Comment by rugk** [comment]
Yes that's my goal. And middle click works - you're right.
However with middle click I also have no animation any more, so it's basically the same as if I just set animation delay to 0.
