### ISSUE TITLE
minimap-titles: new related plugin...

### ISSUE THREAD

**Issue by masavini** [atom-minimap/minimap#391]
Hi,
I've just released a plugin (https://atom.io/packages/minimap-titles) that easily let's you create nice commented ascii-art "titles" readable on the minimap.

If you think it's worth, you may add it to the plugins list...

Many thanks for your excellent work, as well...

**Comment by abe33** [comment]
HI, thank you for the suggestion, but actually your package is not really a minimap plugin. While I agree using ascii-art is a really neat trick when combined with the minimap (you probably noticed I use that extensively in the minimap sources) it's not really interacting with the minimap API (like other plugins do).
And if I were to add your package in the list I would have to add every other packages that do the same (and there's actually quite a bit, including one I wrote myself https://atom.io/packages/search?q=ascii).

What I can do though, is to add a section about using ascii-art with the minimap and add a link to all the packages I know that implement that feature.
