### ISSUE TITLE
make minimap transparent where there isn't code. 

### ISSUE THREAD

**Issue by DavidAwad** [atom-minimap/minimap#392]
it becomes a really annoying problem on split screen with multiple files. Is there a way to remove this problem?

For example I should be able to see all of line 23 that fits in this viewport. 

![screen shot 2015-10-13 at 7 09 02 pm](https://cloud.githubusercontent.com/assets/4019054/10470824/ed1647c4-71dd-11e5-8773-b8ac8b6a67bd.png)

**Comment by abe33** [comment]
Did you take a look at the `Absolute Mode` of the Minimap?

**Comment by fundon** [comment]
Enable `Absolute Mode` or scroll the horizontal bar.
