### ISSUE TITLE
Create standalone minimap without controls

### ISSUE THREAD

**Issue by mrodalgaard** [atom-minimap/minimap#395]
In some cases you do not want to add the minimap controls and scrollbar to your standalone minimap. Currently I am using the following to avoid adding those DOM elements and scroll events to the editor:
```js
atom.packages.serviceHub.consume 'minimap', '1.0.0', (minimapAPI) =>
  minimap = minimapAPI.standAloneMinimapForEditor(@item)
  minimapElement = atom.views.getView(minimap)

  minimapElement.controls?.remove()
  minimapElement.relayMousewheelEvent = ->
```
This seems a bit hacky and it would be nice to e.g. have an options parameter on `standAloneMinimapForEditor` or a method on the returned `minimap` object, which removes this for the user.

**Comment by abe33** [comment]
Have you tried setting `pointer-events: none` on the minimap element? It should prevent any events from being dispatched the minimap.

I also started a PR where I remove every controls in stand-alone minimaps (see #400). If you want to give it a try. I think it make more sense like that, and that allowed me to have a better handling of these elements which means that if we need to change this behaviour in the future it'll be simpler to make the changes.

**Comment by mrodalgaard** [comment]
Thank you. Disabling `pointer-events` works just as good, but feels less of a hack.

#400 works great in my case and is the way I would expect the standalone minimap to work (it also removes the need for setting `pointer-events`). Although I do not know if there would be cases where controls were wanted?

**Comment by abe33** [comment]
Great, I just published a new versions with the PR merged in.

> Although I do not know if there would be cases where controls were wanted?

I don't either, let's go with that for the moment, and we'll see if someone comes up with a different need.
