### ISSUE TITLE
Minimap shrinks too much when opening a file containing long lines

### ISSUE THREAD

**Issue by miraks** [atom-minimap/minimap#399]
Happens on Atom Beta and only when `Tree View` is visible.

![minimap-1](https://cloud.githubusercontent.com/assets/1140675/10854290/dbcdec3a-7f4b-11e5-91d6-f3a96cced8bf.png)
![minimap-2](https://cloud.githubusercontent.com/assets/1140675/10854291/dd42b44c-7f4b-11e5-90cf-99c08e93a0e5.png)

**Comment by abe33** [comment]
Hi @miraks, I've started a PR to support the beta channel, the issue with the layout should be fixed, if you want to give it a try.

**Comment by miraks** [comment]
I've tried this branch and everything seems to work again. Thanks!

**Comment by abe33** [comment]
@miraks Great!, there is still some work on this PR before it gets ready (I need to make sure the tests pass both on stable and beta after all). But given that all but two tests pass I think I'll be able to :ship: the new version during this week-end.
