### ISSUE TITLE
Suggestion: Highlight active line

### ISSUE THREAD

**Issue by sbrl** [atom-minimap/minimap#409]
It would be awesome if  the minimap could optionally highlight the active line.

**Comment by ChaoticMind** [comment]
@sbrl you're probably looking for [this](https://atom.io/packages/minimap-selection). More plugins are listed [here](https://atom.io/packages/minimap)

**Comment by abe33** [comment]
It's just as @ChaoticMind said, using the `minimap-selection` plugin and by activating the `Highlight Cursors Lines` setting.

**Comment by sbrl** [comment]
@ChaoticMind @abe33 Thanks! That's exactly what I needed.
