### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTextEditorScaledHeight' of null

### ISSUE THREAD

**Issue by maplewizard** [atom-minimap/minimap#410]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.16.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getTextEditorScaledHeight' of null

```
At /Users/maple/.atom/packages/minimap/lib/minimap-element.coffee:398

TypeError: Cannot read property 'getTextEditorScaledHeight' of null
    at atom-text-editor-minimap.MinimapElement.update (/Users/maple/.atom/packages/minimap/lib/minimap-element.coffee:398:25)
    at /Users/maple/.atom/packages/minimap/lib/minimap-element.coffee:366:8
```

### Commands

```
     -0:56.1.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:55.3.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:54.3.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:50.8.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  5x -0:50.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:45.9.0 application:new-file (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:44.5.0 pane:show-item-1 (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:43.6.0 pane:show-item-2 (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:43.1.0 pane:show-item-1 (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:42.9.0 pane:show-item-2 (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:41.7.0 pane:show-item-1 (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  5x -0:36.1.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:18 application:add-project-folder (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:04.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ]
  },
  "minimap": {}
}
```

### Installed Packages

```coffee
# User
mathjax-wrapper, v0.1.0
minimap, v4.16.0
remote-edit, v1.8.22
tab-numbers, v0.3.0
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by jamen** [comment]
I'm getting this issue too.  For me it has to do with the `git-plus` package after making a commit.

**Comment by joseluisq** [comment]
I have this issue too when I close a project.

**Comment by franholmo** [comment]
+1  @jamen

**Comment by jamen** [comment]
I think it has something to do with a window being destroyed.

For instance, with the origin of my issue on the `git-plus` package.  Commits are made through a new text editor opening in the window; however, when you save the window is destroyed programatically through the `git-plus` package.  I think minimap doesn't know how to handle this.

I'm not exactly sure, but that's my best guess.  Hopefully that makes it easier to narrow down.

**Comment by abe33** [comment]
I think it's another case of failed update of custom elements, because in 4.16 it should not be possible to enter in the `update` method if there's no `Minimap` model for a `MinimapElement` (which can happen if an update is requested and the minimap got destroyed in the same frame, on the next frame the update will be triggered but the model has already been destroyed): https://github.com/atom-minimap/minimap/blob/v4.16.0/lib/minimap-element.coffee#L378

Let me know if you still get this error after reloading Atom.

**Comment by jamen** [comment]
Works fine now.

**Comment by jamen** [comment]
Never mind, the error popped back up after using it for a while.

**Comment by abe33** [comment]
@jamen  Hmm, that's really weird... how is that possible, are you sure you're running v4.16?

**Comment by jamen** [comment]
Yes:

![](http://i.imgur.com/ELVqCzu.png)

**Comment by abe33** [comment]
And about the stack trace? It's also in `minimap-element.coffee:398`?

**Comment by jamen** [comment]
Yeah.

**Comment by jamen** [comment]
I uninstalled and reinstalled, it works fine again like last time.  I'll see if it comes up again.

**Comment by jamen** [comment]
Yeah...  It appeared again.  I think it only works the first time.  

I don't think it's too helpful, but here is the full stack trace:
```
TypeError: Cannot read property 'getTextEditorScaledHeight' of null
    at atom-text-editor-minimap.MinimapElement.update (/home/jamen/.atom/packages/minimap/lib/minimap-element.coffee:398:25)
    at /home/jamen/.atom/packages/minimap/lib/minimap-element.coffee:366:8
```

**Comment by abe33** [comment]
Thank you for your time, I'll try to think about why it failed, but it's really weird, because the minimap is accessed before this line so it means there's concurrent code that systematically removes the minimap at the same point in time (which is really surprising because race conditions are generally unpredictable).

In the mean time I'll push a patch where I'll store the minimap at the start of the function and use that local version to prevent this error.

**Comment by abe33** [comment]
Ok, I just published v4.16.1, we'll see if it helps.

**Comment by jamen** [comment]
Yup, that fixed it.  :+1:

**Comment by SajeOne** [comment]
I get this error when trying to commit with git plus.

Stack Trace:
/home/<USER>/.atom/packages/minimap/lib/minimap-element.coffee:393
Hide Stack Trace
TypeError: Cannot read property 'getTextEditorScaledHeight' of null
    at atom-text-editor-minimap.MinimapElement.update (/home/<USER>/.atom/packages/minimap/lib/minimap-element.coffee:393:5)
    at /home/<USER>/.atom/packages/minimap/lib/minimap-element.coffee:367:5

If there's anything else I can do to help let me know.

**Comment by abe33** [comment]
@SajeOne Please reload Atom after an update, as far as I can tell you were still running the code from 4.16 (line 493 doesn't match the error https://github.com/atom-minimap/minimap/blob/v4.16.1/lib/minimap-element.coffee#L393).

Let me know if you still get this issue.
