### ISSUE TITLE
Keyboard-friendly minimap

### ISSUE THREAD

**Issue by i90rr** [atom-minimap/minimap#439]
Hi,
Is there any way to access and navigate the minimap via the keyboard?
Thanks.

**Comment by fundon** [comment]
Look at this: https://github.com/atom-minimap/minimap#key-bindings.

**Comment by abe33** [comment]
@i90rr What kind of controls would you expect on keyboard?

**Comment by i90rr** [comment]
@abe33 Hi! I apologize for the late reply, I'm not sure why I wasn't automatically subscribed to the issue.
Anyway, my idea was to be able to navigate the minimap using the arrow keys as well the PgUp/PgDown ones; I was also looking for a way to switch Minimap off and I see that's already covered in the link you kindly shared, many thanks!
