### ISSUE TITLE
The problem with the display of lines when scrolling.

### ISSUE THREAD

**Issue by Bilexes** [atom-minimap/minimap#440]
In the initial position of the page all the lines clearly visible, but after a little scroll they start smearing (see picture). Can this be fixed?
![img](https://cloud.githubusercontent.com/assets/7031555/11976334/5f5210f2-a988-11e5-87e8-127bb2c31159.png)

**Comment by abe33** [comment]
Are you talking about the scroll inside the minimap? 
If yes, that's not really something we can fix without side-effect. We're using CSS transform to have a smooth scrolling, but that means the canvas will have a y position with a float, and in that case, chrome will smooth things despite the fact we have disabled smoothing on the canvas.
The alternative would be to use rounded values for the y position. In fact, the early version of the canvas-based version was working like that, but the result was a poor scrolling effect with the minimap kinda jumping between lines.
So in the end we're really dependent of Chromium behavior for that.

**Comment by Strel0kk** [comment]
Yes, scroll inside the minimap.
I like to use the minimap with 1px line height, but in this case, minimap scrolling looks bad. With 2px line looks better.
Thanks for the answer. Pity that nothing can be done about it.
A good editor, but now a lot of small defects compared with the sublime text )

**Comment by abe33** [comment]
After checking how ST behaves, it appears it doesn't even try to smooth things. So I added a setting to enable/disable the smooth scroll in v4.19.
