### ISSUE TITLE
The Minimap shows only bars not text

### ISSUE THREAD

**Issue by cjpoor** [atom-minimap/minimap#443]
Instead of text I see word-sized(?) bars (solid rectangles) in Minimap.
Macbook Air OS X 10.10.5, Atom 1.3.2

**Comment by abe33** [comment]
Yes, that's the idea, rendering text in a canvas is a really costly operation and given the size at which the minimap operates this cost wasn't justified so we're just drawing rectangles on a canvas.

**Comment by cjpoor** [comment]
OK. Thanks for that clarification.
