### ISSUE TITLE
Can not install by apm

### ISSUE THREAD

**Issue by zalath** [atom-minimap/minimap#447]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\Administrator\AppData\Local\atom\app-1.4.1\resources\app\apm\bin\node.exe" "C:\Users\Administrator\AppData\Local\atom\app-1.4.1\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Administrator\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Administrator\.atom\.apmrc" "install" "C:\Users\ADMINI~1\AppData\Local\Temp\d-116029-9196-18f3yj4\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\Users\Administrator.atom.apm\mixto\1.0.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\Administrator.atom.apm\mixto\1.0.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by zalath** [comment]
Sorry, I try it on my win10, it works really cool. Maybe somethind wrong with my win7.^_^

**Comment by abe33** [comment]
Hi @zalath, it looks like the `package.json` file generated after the install have been somehow corrupted, have you tried reinstalling the package after removing the directory?
