### ISSUE TITLE
adjustMinimapWidthToSoftWrap does not work as intended

### ISSUE THREAD

**Issue by mrleblanc101** [atom-minimap/minimap#452]

**Comment by abe33** [comment]
If you want me to fix a bug, please at least describe what the problem is properly.

**Comment by mrleblanc101** [comment]
I have character width of 2px and soft wrap to 120 character
I activated adjustMinimapWidthToSoftWrap but the width of the minimap did not change
So if i have more than 60 charcter on a line, they disapear in the nether...
I think it's because adjustMinimapWidthToSoftWrap does not take into account the character width option

**Comment by abe33** [comment]
Ok, I see the issue now. there's a condition in the minimap to prevent it from taking more space than what it would take without the `adjustMinimapWidthToSoftWrap` setting enabled. For instance, in your case the minimap should take 240px based on the preferred line length, but at the same time the limit is set to 10% of the editor's width so it won't go past that limit.
Initially this features was added to make the minimap smaller, but I didn't thought that someone would want to use it to make the minimap larger.

Can you try to solution provided in #428 to increase the limit of the minimap (let say 50%) to see if it works for you, I'll see if patching see is possible.
