### ISSUE TITLE
ability to change layer order

### ISSUE THREAD

**Issue by naldir** [atom-minimap/minimap#453]
I now have several plugins to minimap:
find and replace, git diff, highlight selected, pigments, selection...
The selection plugin renders above git diff while I want it to render below.

So it would be useful to add the possibility to manually order layers in the config options

**Comment by abe33** [comment]
Make sense, not sure how I can do that right now, I'll have to think a bit about that.

**Comment by abe33** [comment]
It's now available in v4.20, it works mostly like CSS z-index. But please note that this only apply on each render layer, it means that you won't be able to make a background decoration appear above a foreground one. But for your case (selection VS git-diff) it'll work as both plugins are adding background decorations.
