### ISSUE TITLE
Minimap cause text in input fields of atom settings to be cut off (when using panes)

### ISSUE THREAD

**Issue by sporsh** [atom-minimap/minimap#454]
Reproduce:
- use two panes
- in the left pane: have a file with minimap
- in the right pane: open atom's settings
- make sure tree-view is visible
- observe that the left most part of text (in any input field) is cut off with the same width as the tree-view width.

Probably better explained with some screenshots.
Notice how the first part of e.g. the placeholder for the `Ignored Names` settings field with the text `Default: .git, .hg, .svn, .DS_Store, ._*, Thumbs.db` is cut off by the same amount as the width of the tree view.

![placeholders](https://cloud.githubusercontent.com/assets/1416154/13432512/3e86fa3c-dfce-11e5-8977-9d3d383528c5.gif)

I assume this to be an issue with minimap as I can't reproduce when I disable the minimap package.

Seems to be a corner case bug, but it's annoying as I usually always split my editor in two panes, and for some reason I tend to open settings in the rightmost pane. I have not noticed this happening anywhere else, but I guess the bug could have other impacts as well(?)

Minimap version 4.19.0 (I've seen this way back, but have not looked into it before now)

**Comment by abe33** [comment]
Hi @sporsh, I'm not really sure if the minimap can have this kind of side-effect, I don't see this on my config and I'm also using minimap with the one dark theme.

Have you tried to inspect the mini text editors in the settings view to see where the offset where coming from?

**Comment by sporsh** [comment]
Hi @abe33,

I was running this on my linux box before, but just tried it on a mac with a fresh atom and nothing but the minimap package as well.

I noticed that it did not happen before I scaled my tree-view really wide here, and it seems to depend on the size of the atom window as well. Just going into packages->minimap->toggle to disable minimap seems to remove the issue.

![placeholders2](https://cloud.githubusercontent.com/assets/1416154/13461170/3ddbbbc4-e080-11e5-8d93-34aca163a3c4.gif)

It's weird, as there is no suspicious styling or anything overlapping the text as far as I can see when inspecting the mini text editor. Also, giving focus to any field with cut off text, makes it visible (for that field only)

**Comment by abe33** [comment]
I can reproduce the disappearance of the placeholder, but not the offset you showed me in the first screenshot. There might be some really weird pollution by the minimap so I'll take a look at that when coming back home this evening.

**Comment by sporsh** [comment]
Thanks @abe33!
Not sure if it matters, but note that it does not only affect placeholders but actual values as well (if entered)

**Comment by abe33** [comment]
Right, thanks for the precision.

**Comment by abe33** [comment]
I've tried everything I thought of and didn't find any clue as to why it behaves like this. There's no pollution from minimap styles and no extra markup that could explain this. I would bet for a rendering issue in chromium but It's just a wild guess for the moment.

**Comment by sporsh** [comment]
After upgrade to recent atom-beta releases I'm not able to reproduce this any more.
@abe33 I support your suspicion that this was linked to a chromium rendering issue and not a problem with minimap itself. Closing based on this.
