### ISSUE TITLE
Scroll past end in a grammar causes the minimap to jump when moved.

### ISSUE THREAD

**Issue by PJB3005** [atom-minimap/minimap#456]
**Without** scroll past end set enabled in the grammar:
![](https://dl.dropboxusercontent.com/u/107028026/ShareX/2016/03/atom_2016-03-04_17-21-05.png)

**With** scroll past end enabled in the grammar:
![](https://dl.dropboxusercontent.com/u/107028026/ShareX/2016/03/atom_2016-03-04_17-21-47.png)

I clicked on around the same spot both times. With scroll past end moving in the slightest causes the minimap to jump down. The code editor scrolls down too.

The size of the jump gets smaller with larger files, I assume this is because the extra space added by scroll past end is smaller relative to the file.

Tested on both default grammars (JS) and a custom one.

**EDIT:** I just enabled scroll past end globally in Atom, and the bug doesn't appear to happen.

**Comment by abe33** [comment]
Right, nice catch, I should make sure to use scoped settings when looking for this kind of thing. I'll how easy to change that behaviour.

**Comment by abe33** [comment]
The minimap should now handles properly scoped setting for scroll past end.
