### ISSUE TITLE
Smooth scrolling causes flicker

### ISSUE THREAD

**Issue by keathmilligan** [atom-minimap/minimap#457]
When "Smooth Scrolling" is checked, the minimap flickers pretty badly on Windows when you scroll. The flickering is present, but less noticeable on Mac OS X.

**Comment by abe33** [comment]
Hi @keathmilligan, I guess this is the side-effect of the sub-pixel anti-aliasing applied to the minimap's canvas. When activated this setting use a CSS transform to offset the canvas accurately regarding the editor's scroll, but then the browser need to render some pixel at a floating position which in return gives a blurry aspect to the minimap. The succession of going through full coordinates then floating ones may trigger these flickers (as the overall contrast will vary when sub-pixel anti-aliasing is activated). I would suggest to turn off this setting as it's not really something I can control at the minimap level, I have already turned off any smoothing on the canvas used in the minimap but this is now a browser rendering issue.
