### ISSUE TITLE
Bold font does not appear different

### ISSUE THREAD

**Issue by kbrose** [atom-minimap/minimap#463]
Bold font is displayed the same way as regular font.

![image](https://cloud.githubusercontent.com/assets/4053170/14221322/8a9d55b8-f82b-11e5-9341-759825913308.png)

**Comment by abe33** [comment]
Yeah, we're not really rendering text here, instead we draw rectangles for tokens and words and so we only need to get the color of the text.

I don't really see a way to differentiate bold/italic easily and I'm not sure about the added value of doing so. So I'll close it as wontfix.
