### ISSUE TITLE
New buffers always have a minimap even when toggled

### ISSUE THREAD

**Issue by nixpulvis** [atom-minimap/minimap#466]
I'm not 100% sure of all use cases, and the current correct behavior for the toggle command. But I'd like a keybinging (currently `minimap:toggle`) for turning off the minimap on all panes/buffers. This includes new buffers I create.

**Comment by abe33** [comment]
Hi @nixpulvis,

> But I'd like a keybinging (currently minimap:toggle) for turning off the minimap on all panes/buffers. This includes new buffers I create.

This is what it's supposed to do, and this what I get on my computer, can you give me more information about your config (atom version, minimap version, minimap settings, etc)?

**Comment by nixpulvis** [comment]
```
Atom: 1.6.2
Minimap: 4.21.0
```

I have my minimap on the left, independent scrolling is enabled, and I have a few plugin, namely bookmarks, cursorline, find-and-replace, git-diff, highlight-selected and selection.
