### ISSUE TITLE
mark changed lines

### ISSUE THREAD

**Issue by jimmywarting** [atom-minimap/minimap#467]
would be cool to see what lines are changed in the minimap as well. much like sublime+git package

<img width="470" alt="screen shot 2016-04-11 at 09 57 15" src="https://cloud.githubusercontent.com/assets/1148376/14420360/f91eadbe-ffcb-11e5-8e4d-9921e567a756.png">

**Comment by abe33** [comment]
Hi @jimmywarting, please take a look at the [plugins section of the README](https://github.com/atom-minimap/minimap#available-plugins), you'll find a [git diff](https://atom.io/packages/minimap-git-diff) one in the list.

**Comment by jimmywarting** [comment]
Thanks abe33!
Didn't see that there is plugins for plugins. 
I'm new to Atom

**Comment by abe33** [comment]
@jimmywarting No pb :)
