### ISSUE TITLE
Add option to allow dragging immediately after clicking in a new spot on the minimap

### ISSUE THREAD

**Issue by janneraiskila** [atom-minimap/minimap#469]
Currently you can't skip to a new spot in the minimap and start dragging from there in one click. You have to click twice: first to jump to the new position and then a second time to start dragging the box.

**Comment by ChaoticMind** [comment]
That's because that behavior stops making sense when your document is large enough that the minimap needs to scroll. (Give it a try on a large file)

An alternative is to middle click, then you'll be able to keep dragging.

**Comment by abe33** [comment]
Thanks @ChaoticMind, I was carried away and forgot to reply. 

@janneraiskila That's exactly as @janneraiskila said, it becomes really erratic when the minimap is taller than the available space.

**Comment by janneraiskila** [comment]
I use Apple devices so I unfortunately don't have a middle mouse button.

Is this the only thing middle mouse does differently from left mouse? If so, I still think it would be worthwhile to have an option, settable in a configuration file, to have left mouse click behave like a middle mouse click.
