### ISSUE TITLE
**Code glance** could not work well with **Independent minimap scroll**

### ISSUE THREAD

**Issue by perphyyoung** [atom-minimap/minimap#470]
When enable **independent minimap scroll**, the **code glance** are not enabled when scrolling. Yet move the pointer will cause minimap reset to the pre-position.

**Comment by abe33** [comment]
Hi @perphyyoung, I'm not sure there's anything I can do at the minimap level. It would be a bad design decision to make the minimap behaviour differs depending on installed packages. I saw it was reported in olmokramer/atom-minimap-codeglance#22, we'll see if @olmokramer needs some changes or not but I guess there might be no need for that.
