### ISSUE TITLE
Toggle minimap won't bring minimap back

### ISSUE THREAD

**Issue by tumido** [atom-minimap/minimap#471]
In a situation when the minimap has been hidden and you want to have it displayed again, you can't. Running minimap:toggle has no effect (unless you do something like resize whole window to force a redraw of the minimap).

It's due to [this commit](https://github.com/atom-minimap/minimap/commit/07dbde8c83163f6cc0e1f5af99ac292792a7c5f3) I suppose.

**Comment by abe33** [comment]
What did you do to had the minimap hidden? Running `minimap:toggle`?

Because this is not what I observe: 
![minimap-toggle](https://cloud.githubusercontent.com/assets/247140/14583481/3f1daf3a-0423-11e6-9aad-a43117883e3f.gif)

Also, the commit you're linking to is totally unrelated, it just prevent the minimap from requesting a full repain when the `ignoreWhitespacesInTokens` setting is retrieved/changed and the minimap is not yet attached to the DOM.

**Comment by tumido** [comment]
Yes, that's what I did. The commit was just a rough guess, sorry if it's a blind end. The issue occurred today after the upgrade of minimap. That's why I think it should be some kind of regression somewhere (and this commit seemed as the best fit for the cause so sorry if it's not).

Well yes, that's what I did. I ran `minimap:toggle` and then when I did `minimap:toggle` again the minimap stayed unfortunately hidden. I've disabled all other packages I had to make sure it's not caused by any third party and it seems it's not.

This is my GIF for you lol :)
![minimap_toggle](https://cloud.githubusercontent.com/assets/7453394/14583721/f8de78c6-042a-11e6-8644-a63480fd1b58.gif)

Is there any way how can I help you? Any logs to send?
minimap v4.22.1
atom v1.7.0
amp v1.9.2
electron 0.37.5

**Comment by abe33** [comment]
> Is there any way how can I help you? Any logs to send?

The minimap config you're using would surely help a lot, and if you know a bit about CSS and the chrome devtools you can try to inspect the text editor content to see if the minimap is present in the DOM and to see if it doesn't have some styles applied that could explain why it doesn't appear properly.

> I've disabled all other packages I had to make sure it's not caused by any third party and it seems it's not.

Themes can also have an effect on the minimap if they meddle with the text editor flex layout, but so far no one reported issues about that so I guess most themes don't touch this part at all.

**Comment by tumido** [comment]
I've tried it also without "any config" at all. I've removed the  config `.atom` folder (so Atom creates a new one on its startup). Then I've installed the `minimap` package via integrated pkg manager. Just that nothing else and the result was the same.

That means (in my eyes) it's not config specific or related to any other package. My Atom version, the exact same packages I'm using, can be found in this [Copr repository for Fedora](https://copr.fedorainfracloud.org/coprs/mosquito/atom/).

When it comes to the DOM inspector: I did the investigation there and the minimap is added or removed correctly with every `minimap:toggle` command. It seems it's just shown in wrong position - placed out of sight. But when window is resized or maximized it's fine and the minimap is where it should be.

**Comment by tumido** [comment]
Ok, after some experiments with the DOM inspector I've found that when I have the **absolute mode** enabled it works fine, otherwise it's not. When the **absolute mode** is disabled it's positioned out of the sight and I still need to resize the window.

It also does something weird for every other tab than the open one, because there you can find multiple nodes for the minimap (a node per each `minimap:toggle` when "show minimap" suppose to happen). This is probably related to the atom sessions, when you start the editor and some tabs are opened - remembered from previous session, but their content is not yet listed in the DOM. Imagine a scenario:
1) you have a couple of tabs opened
2) close the editor and open it again
3) on the current tab show and hide your minimap
4) activate another tab
5) in the DOM inspector you're gonna see multiple minimap instance (in case you did hide and show once, there gonna be two minimap nodes etc.) - one created by the tab restore and one for each "show minimap" action.

![minimap](https://cloud.githubusercontent.com/assets/7453394/14591413/6811f902-0511-11e6-81d8-49ca3c9891d4.png)

**Comment by abe33** [comment]
Could you tell me which theme you're using to see if I can reproduce that on my computer?

**Comment by tumido** [comment]
It's not theme related. The issue is present for me with any theme including the default One Dark. As I said, I tried it also with completely clean setup, with freshly generated `.atom` folder. So It's not related to any theme or any other package. The problem can only be somewhere in my Atom build or in the minimap itself. And as you can't reproduce it on your setup, I'm thinking that the problem is more likely in my Atom than in the minimap. What version of Atom do you have?

**Comment by abe33** [comment]
Currently I'm running master (`1.9.0-dev-8ece1ee`) but there was no change on this part since 7 months ago (v4.15.2 of the minimap, probably around atom 1.4 or 1.5). 

It's definitely weird that some instances are not properly remove on toggle, there should always be only one minimap per editor, and only one view per minimap. I guess there's no errors in the console neither?

**Comment by gregorskii** [comment]
Seeing the same. Mine will not toggle back in.

**Comment by tumido** [comment]
OK, the problem has been solved using the prepacked and precompiled Atom package form atom.io. Apparently there's a regression due to some node.js package used by Atom or Electron core. When these libraries are statically linked and included in the Atom binary instead of being a dependency the problem is solved.

I'm closing this issue due to fact it is more a setup issue than a problem caused by this plugin. Thank you for your interest and willingness to help.You're doing a great job on the minimap and I have to admit, you're making a programmer's life much easier. :) Cheers!

**Comment by int3h** [comment]
I'm having the opposite problem: when I toggle the minimap, some buffers end up with two minimap elements (one of which has blank/empty contents, but still takes up space next to the "real" minimap element). 

If I then toggle minimap off, it blanks out the content of the "real" minimap element, but leaves it in the DOM, so now there are two empty minimap DOM elements taking up space on the right of the buffer. Toggling it back on again creates a third ("real") minimap element next to the two empty ones, and so on.

I've reproduced this with all my minimap plugins disabled (in their Atom package settings) and with my entire user stylesheet commented out. I'm using the Atom Beta 1.8.0-beta3, and the latest version of minimap (4.23.5).
