### ISSUE TITLE
Having the minimap package on slows down opening large files to the point where atom becomes unusable

### ISSUE THREAD

**Issue by jasperkennis** [atom-minimap/minimap#473]
Working on a project that has large json files. Atom was becoming very slow and I asked for help on the forum (https://discuss.atom.io/t/some-json-files-open-really-slow/27894/4). After some discussion I figured minimap might be the problem and it turned out it was exactly that; when I disable it Atom behaves fine.

I think this could be tested by just creating a project with very large json files in it and see how Atom behaves.

**Comment by abe33** [comment]
Hi @jasperkennis, can you profile/timeline the editor while running the minimap on this large json?

I just tried on a 170k line, 8MB CSV file and the minimap is running smoothly with less that 2ms per update:

![fielding_csv_ __users_cedric_development_ruby_leclerc-es-v2](https://cloud.githubusercontent.com/assets/247140/14602915/ec8870ea-056a-11e6-88f5-a8cc87fed4e1.png)

By comparison, the huge block on the right is the text editor repaint.

**Comment by jasperkennis** [comment]
Ah, I'll give that a go!

**Comment by jasperkennis** [comment]
Ok, i'll just post my tracking here so you can see what it looks like, but I'm pretty sure it's not related to minimap at all. The giant hole of idle is you tell me what is going on, and it's not only when opening big files, in fact it seems to happen just as often when opening small files. Maybe it's just that the project folders I have open are 8gb... Will run back to discuss.atom.

Thanks for pointing out the profiler!

![screen shot 2016-04-20 at 15 25 37](https://cloud.githubusercontent.com/assets/247177/14676143/6e402a2c-070c-11e6-8ddb-de84bd59099a.png)
