### ISSUE TITLE
Minimap position overlays on code editor

### ISSUE THREAD

**Issue by nickradford** [atom-minimap/minimap#478]
Just noticed this today, there's an extra gutter to the right of the minimap now.

![image](https://cloud.githubusercontent.com/assets/222221/14897277/3c177386-0d36-11e6-93e1-3f7a098ff330.png)

Atom 1.7.3 (OSX)
atom-minimap 4.23.2

**Comment by Ben3eeE** [comment]
This might be https://discuss.atom.io/t/where-did-this-empty-space-come-from-how-do-i-get-rid-of-it/30226. Please try this if you still have the problem.

**Comment by abe33** [comment]
Wow, I completely forgot about that issue, I guess that since it's pretty old the issue was solved in the mean time. I'll wait a few days and close that issue.
