### ISSUE TITLE
Feature request: automatically hide editor scrollbars when minimap is visible

### ISSUE THREAD

**Issue by int3h** [atom-minimap/minimap#479]
The README.md has a nice suggestion on how to hide Atom's native vertical scrollbar. I have this in my styles.less, since the scrollbars are redundant clutter if minimap is enabled:

```css
atom-text-editor,atom-text-editor::shadow { .vertical-scrollbar { opacity: 0; width: 0; }}
```

My frustration comes from the fact that I don't always have the minimap visible. I often toggle it off to save horizontal screen space, like when I'm editing two file side-by-side. 

When the minimap isn't visible, having the native scrollbars visible is quite useful/necessary. An option to "hide native scrollbars" in minimap's settings would be very handy for this, if it was smart enough to hide/unhide them based on minimap visibility.

I'd also settle with some way to use a CSS selector to apply the `opacity: 0; width: 0;` style only to `.vertical-scrollbar` elements inside editors with visible minmaps. I tried and failed to find a way to do this with the current version. (CSS sibling selectors don't work because the editor and it's `.vertical-scrollbar` come before the minimap element, and sibling selectors can only select elements that occur *after* another element.)

**Comment by abe33** [comment]
I've added a `with-minimap` attribute on the text editor hosting a minimap, and updated the README with that, so you should now be able to toggle the scrollbar visibility depending on the presence of a minimap.
