### ISSUE TITLE
Retina + Smooth Scrolling = incorrect height/scroll calculation 

### ISSUE THREAD

**Issue by danielnieto** [atom-minimap/minimap#480]
I noticed this bug since I got a macbook with a retina display, when you have Smooth Scrolling setting turned off the minimap seems "bigger" and all calculations are way off.

![image](https://cloud.githubusercontent.com/assets/2120107/15028219/5d82e164-120d-11e6-9da3-3d43a083dd82.png)

As you can see in the image, those are the default settings for minimap and you can see that the characters look way bigger than they should be... in this example you cannot scroll down further even though you see that there is more stuff below. 

This is fixed by setting Smooth Scroll to true:

![image](https://cloud.githubusercontent.com/assets/2120107/15028298/c5c6b818-120d-11e6-9b92-07d6dae0bc8f.png)

**Comment by abe33** [comment]
Hi @danielnieto 
Interesting, since I don't have access to a Retina device I didn't noticed. I'll take a look because it might just be some scaling missing when smooth scrolling is disabled.
