### ISSUE TITLE
I tried the minimap width CSS code at #428 but it does not work

### ISSUE THREAD

**Issue by vanceaadi** [atom-minimap/minimap#483]
The instructions found at  #428 for changing the width of minimap using CSS do not work on my recent install (I am new to Atom).
"Adjust Minimap Width To Soft Wrap" is disabled.

Atom 1.7.3
minimap 4.23.5
Other community packages are disabled

**Comment by vanceaadi** [comment]
After a 5 hour break it hit me the answer is of course in the code.
Just check out 
https://github.com/atom-minimap/minimap/blob/master/styles/minimap.less

The following code changes the minimap to 5% instead of the default value of 10%
atom-text-editor::shadow, atom-text-editor, html {
  atom-text-editor-minimap {
    &:not([stand-alone]) {
      width: 5%;
      flex: 0 0 5%;
    }
  }
}

For fixed size, just replace 5% with 100px for example.

**Comment by abe33** [comment]
@vanceaadi Yeah you're right, I should probably add a section in the README about that.

The main point to remember is that we're using a flex layout here, and in that context, the width itself isn't completely reliable, hence the use of the `flex-basis` setting (the third value in the `flex` shorthand property).

**Comment by gll89** [comment]
Hi Vanceaadi! I have an issue: where should I put these codes? In styles.less or somewhere else?

Best,
Linlin
