### ISSUE TITLE
Scrolling to the right causes minimap-overlay to scroll out of sight

### ISSUE THREAD

**Issue by H-M-H** [atom-minimap/minimap#484]
![screenshot from 2016-05-21 23-20-42](https://cloud.githubusercontent.com/assets/7461564/15450930/42ab4d7a-1fac-11e6-8d98-acaeb6b6c139.png)

As you see in this screenshot scrolling to the right also scrolls the overlay, which is logical at some point but also annoying as you can not drag it around if it is totally gone. Obviously this happens if the window is small and/or there are overly long lines of code.

Atom: 1.7.3
minimap: 4.24.0

**Comment by Yajo** [comment]
I have noticed that, when left file tree panel is enabled, if I reduce the left panel width, the minimap shows up; but if I increase left panel's width, minimap disappears to the right.

**Comment by abe33** [comment]
Right, I should have anticipated that problem. What do you think of indicating the horizontal scroll with some kind of border so that the left part can still interact with the mouse?

**Comment by H-M-H** [comment]
I guess this is related to #460 which could fix this problem. On the other hand this would probably still look awkward with really long lines as those might bloat the map.

However, the border thingy sounds also fine to me.
