### ISSUE TITLE
Is it possible to add a shortcut to toggle hide and show minimap?

### ISSUE THREAD

**Issue by intijk** [atom-minimap/minimap#485]
I didn't find such feature or plug-in in the plug-in list, is it possible ?

**Comment by abe33** [comment]
There's something approaching available through the `toggle minimap` command, the keybinding however is left to your discretion. Is that what you are looking for?

**Comment by eL-HaXo** [comment]
@abe33 Here from google... I was looking for a keybinding and I assume that @intijk was looking for the same. Thanks for the answer.

**Comment by hhrutter** [comment]
I don't see a keybinding command for `toggle minimap` as of release May 2017 (version 1.13).
Has anybody successfully setup a minimap toggle shortcut?
Thanks.

**Comment by kentukynitemare** [comment]
1. <Control+Shift+P> search "Open Your Keymap" (without quotes)
1. <enter>
1. add a keymapping to the end of that file e.g.
```
'atom-workspace':
  'ctrl-;': 'minimap:toggle'
```
1. Save, you're done.

The Key Bindings section [here](https://atom.io/packages/minimap) was helpful for finding the command name.

**Comment by hankchanocd** [comment]
@kentukynitemare Thanks a bunch. That's what I've been looking for. It's odd that searching for any `minimap` command from existing keybindings doesn't show anything.
