### ISSUE TITLE
Two minimaps appearing superimposed, one scrolls, one does not

### ISSUE THREAD

**Issue by lzkelley** [atom-minimap/minimap#504]
I've been getting some screwy behavior since at least v4.24.6, but possible down to v4.24.4.

atom: 1.9.0-beta0
minimap: 4.24.6

This one is especially interesting:
(Haven't been able to find a consistent way to reproduce)

![minimap-err-1](https://cloud.githubusercontent.com/assets/3839265/16173014/096bbfe6-3563-11e6-8706-3c0d8c0d81e3.gif)

**Comment by abe33** [comment]
I think I can add some guards against doublon. A possible cause might be that after an update within Atom the previous minimaps are not properly destroyed and new ones are created once the package is activated again.

**Comment by lzkelley** [comment]
Hi @abe33, I think you're right about the cause.  I haven't seen it since the first time - right after the update.  It looks like this is a common type of issue with packages right after update.
Thanks!
