### ISSUE TITLE
slide bar can not scroll to bottom and can not drag

### ISSUE THREAD

**Issue by QiiSyhx** [atom-minimap/minimap#507]
![qq 20160628135956](https://cloud.githubusercontent.com/assets/2001704/16405245/a67dd422-3d38-11e6-825c-8127d71cd988.png)

**Comment by victor-web** [comment]
+1  can't  drag  scroll
OS: Windows 10
Atom: Latest

**Comment by abe33** [comment]
Hi there, sorry for the late reply.

I don't have a windows device at the moment, would you be kind enough to use the devtools inspector? it's probably not much, I would bet on some overlap or a `pointer-events: none` somewhere that is polluting.

**Comment by apstemmer** [comment]
+1 
Atom: 1.9.8
Windows 10

**Comment by Ben3eeE** [comment]
This looks a lot like https://github.com/atom/atom/issues/11484

**Comment by Ben3eeE** [comment]
This is a bug in Atom core and has been fixed for the `Atom Light` UI theme in Atom 1.12. It can still happen on Windows with other themes that use native scrollbars but there is nothing you can do in the minimap to fix this.

See https://github.com/atom/atom/issues/11484#issuecomment-243642101 for an explanation.
