### ISSUE TITLE
suggestion: Optionally have cursor jump to minimap click

### ISSUE THREAD

**Issue by crantok** [atom-minimap/minimap#515]
One thing that happens to me occasionally: I click on the minimap to jump to a long way in a file then, after reading the part that I'm looking at, I press PgUp or PgDn and my view of the file jumps to nearly where I left the cursor. I find this momentarily disorienting.

Would it be practical to provide an option for the cursor to follow the view when clicking on minimap?

**Comment by abe33** [comment]
Interesting suggestion, I guess this should be enabled through a package setting.

**Comment by crantok** [comment]
Just updated to minimap 4.25.0 and the new setting worked exactly as expected one I restarted Atom.

Thank you :)
