### ISSUE TITLE
error

### ISSUE THREAD

**Issue by untalrobert** [atom-minimap/minimap#524]
version 4.25.5 is not the latest version available for this package, but It's the latest that is compatible with your version of atom

**Comment by sharifzadesina** [comment]
I have this problem too, and the minimap doesn't show with a lot of console error.

**Comment by daniele-salvagni** [comment]
Had the same message and I can't get the minimap to display, I can't see any console errors though.
Related to #525.

**Comment by sharifzadesina** [comment]
Installing package v4.25.5 with `apm` fixed it for me.

**Comment by fundon** [comment]
If you install the `v4.26.1` then remove this version, and reinstall `v4.25.6` with APM.

**Comment by abe33** [comment]
It's weird, could you file an issue on Atom with reproduction steps because it definitely shouldn't let you install a version that is not compatible with your current Atom version.

**Comment by icdevin** [comment]
This is happening to me. I was on Atom 1.10.x and when I went to install this package, I saw my version of Atom could be outdated (indicated by that message), so I updated Atom to latest (1.11.2 as of now) and saw the message persisted. Strange. So I installed Atom Beta and the message persisted once again, so I thought it may be a bug.

**Comment by abe33** [comment]
Hey all, 1.13 was finally released! Which means that you all will be able to use the v4.26.x versions.
