### ISSUE TITLE
minimap is not working

### ISSUE THREAD

**Issue by mayankc3010s** [atom-minimap/minimap#528]
i have installed minimap on my atom ide but its not working i have latest version of atom yet it fails to work , i want better scrolling experience and i love minimap as i have seen in sumlime text

**Comment by fundon** [comment]
Which version is your minimap?

**Comment by mayankc3010s** [comment]
its Version 1.11.2

**Comment by fundon** [comment]
Thanks, I talked about the minimap?

**Comment by mayankc3010s** [comment]
sorry , its minimap 4.26.1

**Comment by fundon** [comment]
Please re-install minimap to v4.25.6 via `apm`.

**Comment by mayankc3010s** [comment]
i am new to atom i dont know how to install with apm . please will you explore it a bit . and i am very thankful for your cooperation

**Comment by fundon** [comment]
See http://flight-manual.atom.io/using-atom/sections/atom-packages/#command-line.

**Comment by johnnywidth** [comment]
+1, not working for minimap 4.26.1, atom 1.13.0, macOs 10.12.1
For 4.25.6 OK!

**Comment by DawnPaladin** [comment]
I had the same issue on Ubuntu. Installing 4.25.6 via `apm` worked for me. Thanks for the fix!

**Comment by JuanQP** [comment]
I had the same issue and it was solved switching to Minimap v4.25.6

- Windows 8.1 64bits
- Atom 1.11.2

**Comment by tokoiwesley** [comment]
I had the same issue with Atom v1.11.2 on Ubuntu. Uninstalling minimap v4.26.1 and reinstalling v4.25.6 via `apm` solved the problem.

**Comment by abe33** [comment]
I don't really get how you were all able to get version 4.26.1 on Atom < 1.13. Does some of you have the [auto-update-packages package](https://atom.io/packages/auto-update-packages) installed?

**Comment by cbcoutinho** [comment]
I was also able to downgrade to 4.25.6, and now minimap works again - thanks for the tip!

**Comment by wisliyao** [comment]
how to downgrade it to 4.25? 

i come across the same issue after updated it...... i then tried to updated Atom but it doesn't work.

Windows 10 64bits
Atom 1.11.2

**Comment by fundon** [comment]
@wisliyao See https://github.com/atom-minimap/minimap/issues/528#issuecomment-257096535 and https://github.com/atom-minimap/minimap/issues/528#issuecomment-257094872.

**Comment by cbcoutinho** [comment]
Small update - uninstalling minimap on atom 1.12.0 and trying to reinstall it using atom says that the 4.25.6 is the highest available version compatible with atom 1.12.0

I think this a good workaround until the problem is solved - that way you can successfully install minimap through atom for the correct version

**Comment by ramoncardena** [comment]
Just un update here. Using Atom 1.12.2.

Installing through atom the message that @cbcoutinho refers pops up, and you get the 4.25.6 version. But it doesn't works, Mminimap doesn't show up.

I uninstalled through Atom and reinstalled 4.25.6 with apm, and worked like a charm.

**Comment by sleepywill** [comment]
For those having problems.  This appears to be the result of running Atom Beta - the beta updates minimap for both versions.  So when you run the beta, do not update the packages.

**Comment by sebastian-marinescu** [comment]
The command to fix it: 
```
apm install minimap@4.25.6
```

**Comment by abe33** [comment]
@sleepywill That's an interesting find, I'll make sure to report that to the core team.

**Comment by mayankc3010s** [comment]
thanks man version 25 worked for me

**Comment by abe33** [comment]
Hey all, 1.13 was finally released! Which means that you all will be able to use the v4.26.x versions.
