### ISSUE TITLE
What is the minimap's architecture and how to realize the plugin by JavaScript?

### ISSUE THREAD

**Issue by Meloneat** [atom-minimap/minimap#529]
l write a article about how to use a plugin on GitHub. Also,how the minimap can be acknowledge through the code.But facing so many files in minimap, l  don't known how to learn and explain first from where and which is import and which is not(could skip).

**Comment by abe33** [comment]
Hi @Meloneat, are you looking to build a minimap plugin or is it out of curiosity?
