### ISSUE TITLE
Poor performance when active

### ISSUE THREAD

**Issue by hugoamvieira** [atom-minimap/minimap#531]
I've noticed that the minimap slows atom down A LOT when opening files and navigating through them.

Minimap version: 4.25.6 w/ Atom 1.11.2

**Comment by abe33** [comment]
Hi @hugoamvieira, could you provide a timeline profile of the slowdown you experience?

**Comment by hugoamvieira** [comment]
Hello @abe33, sure I'll link it down here.

**Comment by hugoamvieira** [comment]
Weird, I cannot reproduce this anymore.
Anyways, I'll close this and if it happens again I'll be sure to do a repro ASAP :)

Thanks!
