### ISSUE TITLE
Minimap doesn't work when Vim Mode's Normal mode enabled

### ISSUE THREAD

**Issue by kutsan** [atom-minimap/minimap#532]
I use vim-mode-plus and as I mentioned in the title when I switch to normal mode, minimap disappears. Also, absolute mode enabled.

**Minimap:** 4.25.6
**Atom:** 1.11.2

![](https://i.imgur.com/Ne3FIgE.gif)

**Comment by abe33** [comment]
It looks like some z-index conflict, could you confirm that using the chrome devtools?

**Comment by Kutsan** [comment]
Nope, z-index looks okay. 409ee1a worked for me.
