### ISSUE TITLE
Mini map not displaying code in map

### ISSUE THREAD

**Issue by jf0772256** [atom-minimap/minimap#535]
I have been using Minimap since i began using atom, I love it, and it may just be my computer but it is not displaying anything in the map its self which is only really a minor irritation due to the fact that the rest of the map works like it always has...

**Comment by fundon** [comment]
See https://github.com/atom-minimap/minimap/issues/528.

**Comment by abe33** [comment]
Hi @jf0772256, we'll need more details such your Atom's version, the Minimap's version, etc.

**Comment by jf0772256** [comment]
I must have had a bad version or dl of the mini-map, I uninstalled and reinstalled it again, and it started working... Mini-Map is 4.25.6 and Atom is 1.12.3.
