### ISSUE TITLE
Minimap increases the load/start-up time

### ISSUE THREAD

**Issue by SRvSaha** [atom-minimap/minimap#537]

**Comment by abe33** [comment]
Hi @SRvSaha, without more information such as timecop infos or a startup profile I can't du much cause I don't see much impact of minimap on startup (6ms to load, 200ms to activate with a bunch of editors open)

**Comment by Kimamisa** [comment]
Hi @abe33. I'm facing the same performance issue: the plugin added 2686ms to startup time. What kind of report / logs can I provide to investigate this issue ?

**Comment by Kimamisa** [comment]
Also it is worth mentioning that it only appears the first time Atom is loaded after a reboot.

**Comment by aminya** [comment]
Good news: I got access to minimap. I am adding all the performance patches I added to minimap-plus to minimap. So, this is/will be fixed.
