### ISSUE TITLE
minimap not working on MacOS 10.12.1 and Atom 1.12.3

### ISSUE THREAD

**Issue by Raydem0n** [atom-minimap/minimap#539]
minimap not working on MacOS 10.12.1 and Atom 1.12.3

**Comment by Raydem0n** [comment]
maybe conflict with ActivePower plugin. Disable active-power and re-install minimap fix the issue.

**Comment by abe33** [comment]
Looks like a duplicate of #541 for me, could you confirm that downgrading to v4.25.* fix that issue?

**Comment by abe33** [comment]
Hey all, 1.13 was finally released! Which means that you all will be able to use the v4.26.x versions.
