### ISSUE TITLE
Minimap not working

### ISSUE THREAD

**Issue by sudguru** [atom-minimap/minimap#540]
I have latest version of atom installed yesterday. Then I installed minimap via atom settings. Uninstalled it and tried apm. But still not working.

**Comment by darkdragon-001** [comment]
Same problem here.

Atom 1.12.3 and minimap 4.26.3. Developer console does not show any problems...

**Comment by darkdragon-001** [comment]
#528 (downgrade to 4.25.6) solved my problem.

**Comment by sebastian-marinescu** [comment]
The command to fix it: 
```
apm install minimap@4.25.6
```

**Comment by abe33** [comment]
Thanks @sebastian-marinescu for answering there, I'm closing it in favor of #528
