### ISSUE TITLE
install minimap and not working

### ISSUE THREAD

**Issue by rroderickk** [atom-minimap/minimap#541]
Not working my minimap 4.26.3 on my Atom 1.12.3

**Comment by MrBlaise** [comment]
My minimap won't show as well on 1.12.3 and 1.12.2

**Comment by miszo** [comment]
My minimap also doesn't work. I have atom in version: 1.12.5. Workaround given by @MrBlaise also didn't helped.

**Comment by lumpyzhu** [comment]
macOS Sierra version 10.12.1, atom 1.12.5, minimap not work.

**Comment by mattiascaricato** [comment]
@MrBlaise  thanks!

**Comment by abe33** [comment]
How did you install this version of the minimap?

v4.26 should only be available for Atom 1.13+ (current beta). Due to a breaking in change in Atom there's no way to get a version that works in both pre-v1.13  and v1.13  versions.

**Comment by ChangeLeon** [comment]
@MrBlaise 谢谢 3ks

**Comment by Cesar456** [comment]
my minimap doesn't work too.
windows 10 x64
atom v1.12.6
mimimap 4.25.6
so depressing...

**Comment by FreeWebber** [comment]
Same
Linux Mint Mate 18
Atom 1.12.6
Minimap 4.26.3
Strange, on other LM, but KDE works fine!

**Comment by carlossuazo** [comment]
I had already installed minimap but didn't work, I just run this in command line this : 

>apm install minimap

this is in windows 7

**Comment by miszo** [comment]
Hi, I've updated minimap do 4.25.7 on my atom 1.12.5 and it works!
my pc: Windows 10 x64

**Comment by Bnmkt** [comment]
Hi,
downgrading Minimap to 4.25.6 on atom 1.12.6 works for me.

**Comment by BLamy** [comment]
MacOS Sierra 10.12.1
Atom 1.12.6
Installing through preferences didn't work. 
Downgrade to 4.25.6 works

**Comment by lvchangqi** [comment]
Atom 1.12.7
windows 10 x64
 `apm install minimap@4.25.7`
but it doesn't work

**Comment by MrBlaise** [comment]
Atom 1.12.7
windows 10 x64
minimap 4.25.7
works perfectly, the problem was fixed for me with the latest atom and latest minimap, maybe reinstall atom and see if it helps

**Comment by abe33** [comment]
Hey all, 1.13 was finally released! Which means that you all will be able to use the v4.26.x versions.
