### ISSUE TITLE
Uninstall issues

### ISSUE THREAD

**Issue by jha-ayush** [atom-minimap/minimap#545]
Hi,
I've tried to uninstall/disable minimap numerous times from Atom. But everytime I restart Atom, minimap appears again.
Please advice as to how to permanently remove minimap from Atom!

**Comment by ricardoccpaiva** [comment]
any news on this ?

**Comment by jha-ayush** [comment]
Still have the same issue. Minimap re-installs everytime Atom restarts.

**Comment by ricardoccpaiva** [comment]
try this:  open your `config.cson` file, search for `minimap` and remove that line(s).
so far so good from my side, give it a try @jha-ayush 👍
