### ISSUE TITLE
Minimap not showing up..

### ISSUE THREAD

**Issue by yadu007** [atom-minimap/minimap#546]
Minimap not Showing up even after trying Minimap  toggle.!

![newwwwwwwwwwwwwwww](https://cloud.githubusercontent.com/assets/20080320/22008510/ef40fcbc-dca1-11e6-874f-e71e643ea2dc.PNG)

**Comment by wabudd1** [comment]
Same.  I'm also seeing when installing "Version 4.25.7 is not the latest version available for this package..." even though it appears there is no newer version.

**Comment by skaraman** [comment]
same

**Comment by arielhasidim** [comment]
same

**Comment by abe33** [comment]
What's your version of Atom and what's the version of the minimap?

**Comment by arielhasidim** [comment]
1.12.6

**Comment by yadu007** [comment]
atom 1.12.6
minimap 4.26.1

**Comment by arielhasidim** [comment]
sorry
atom - 1.12.6
minimap - 4.26.4

**Comment by tim-berry** [comment]
I'm also facing this issue.

Windows 10
Atom - 1.12.7
minimap - 4.26.1

**Comment by mohan31** [comment]
Same here please solve 
Windows 10
Atom - 1.12.7
minimap - 4.26.4

**Comment by GloverDonovan** [comment]
Same issue here.
Windows 10
Atom 1.12.7
minimap - 4.26.4

**Comment by Cmd-Cmd** [comment]
Same issue here.
Windows 10
Atom 1.12.7
minimap - 4.26.4

**Comment by pranjalchaubey** [comment]
Same issue here. 
Windows 7 64-bit
Atom 1.12.7
Minimap 4.26.1

**Comment by lukeha** [comment]
Same issue here.
Windows 7 64-bit
Atom 1.12.7
minimap 4.26.3

**Comment by ScientiFist** [comment]
same issue

**Comment by lukeha** [comment]
But OS X is OK:
OS X El Capitan 10.11.6
Atom 1.12.6
minimap 4.25.7

**Comment by abe33** [comment]
For everyone that have `v4.26.x` on Atom `1.12.x`, you should downgrade to `v4.25.x`.

@yyuuliang Are you sure you're running v4.25 and not v4.26? If so it could be a totally different issue

**Comment by mohan31** [comment]
working now with v4.25.7

**Comment by ScientiFist** [comment]
Yeah its working on v4.25.7 on atom 1.12.X and archlinux :)

**Comment by ummahusla** [comment]
Broken for me. 

Atom `1.12.7` and minimap `4.26.5`

**Comment by cheanss** [comment]
Same issue
Windows 7 64-bit
Atom 1.12.7
Minimap 4.26.5

**Comment by pranjalchaubey** [comment]
How do I 'downgrade' my 4.26.1 version to 4.25.x ??

**Comment by abe33** [comment]
@pranjalchaubey 

`apm uninstall minimap && apm install minimap@4.25.7`

**Comment by rogueacademic** [comment]
Same issue
Windows 7 64-bit
Atom 1.12.7
Minimap 4.26.5

**Comment by HornyakBence** [comment]
Had the same issue. 
Downgrade helped. 
Thanks!

**Comment by kingRayhan** [comment]
I updated to `v 1.12.9` but still have the problem 😢

**Comment by abe33** [comment]
Hey all, 1.13 was finally released! Which means that you all will be able to use the v4.26.x versions.

**Comment by Chronophylos** [comment]
I have 
Windows 10 64
Atom 1.14.1
Minimap 4.26.8
Vim-Mode-Plus 0.82.0

Minimap only shows up in Insert mode of Vim-Mode-Plus.
When I disable or uninstall Vim-Mode-Plus Minimap never shows up.
Downgrading didn't help but made Deprecation Cop react.
