### ISSUE TITLE
Minimap not toggling on but not producing any errors

### ISSUE THREAD

**Issue by Lite5h4dow** [atom-minimap/minimap#548]
i am running atom along with my atom editor, however minimap doesent run in editor at all, i cant toggle it isint CTRL+Shift+P - Minimap - Toggle Minimap

**Comment by KTsarlz** [comment]
Install version 25 then update, that worked for me.

**Comment by abe33** [comment]
Hey all, 1.13 was finally released! Which means that you all will be able to use the v4.26.x versions.

**Comment by KTsarlz** [comment]
@abe33 I still get that I have the latest version 1.12
