### ISSUE TITLE
minimap not showing up

### ISSUE THREAD

**Issue by camillevillnv** [atom-minimap/minimap#550]
I have Atom 1.12.7
Installed minimap v 4.25.7
Toggle option doesn't do anything
No errors

- Windows 10

**Comment by Wjk2a1** [comment]
same here

**Comment by MillerL** [comment]
same problem

**Comment by Piguel** [comment]
Same Here. Minimap not showing up.
macOS 10.12.1
Atom 1.12.7
Minimap v 4.26.4

**Comment by topjor** [comment]
same here, just installed atom and minimap, but won't show up

**Comment by MrAlexSee** [comment]
Same here. Atom 1.12.7, minimap 4.26.4, Windows 10 64-bit.

**Comment by Hello2Jason** [comment]
Same here
Atom 1.12.7
minimap 4.26.4
windows 10 64

**Comment by abhisheknalin** [comment]
Uninstall latest minimap and use version 4.25.7 with Atom version 1.12.x

apm install minimap@4.25.7

**Comment by Sawtaytoes** [comment]
That fixed it. For some reason, it auto-installed the latest version on my desktop even though on my tablet it didn't. Both of them I manually installed by clicking "Install" in Install Packages and both displayed the same warning about the version number being installed being older than the latest so it's compatible.

Both systems also Win10 64-bit.

**Comment by Sawtaytoes** [comment]
That fixed it. For some reason, it auto-installed the latest version on my desktop even though on my tablet it didn't. Both of them I manually installed by clicking "Install" in Install Packages and both displayed the same warning about the version number being installed being older than the latest so it's compatible.

Both systems also Win10 64-bit.

**Comment by ummahusla** [comment]
Broken for me as well. 

Atom `1.12.7` and minimap `4.26.5`

**Comment by Billybobbonnet** [comment]
Same setup, same problem.

Disabling minimap related plugins (minimap-pigments, minimap-highlight-selection and  minimap-selections) after applying the fix from @abhisheknalin solved this. 

I wish we had an update here to know when we can update to the latest version.

**Comment by classLfz** [comment]
Same here
Atom 1.12.7
minimap 4.26.5
ubuntu16.10 64

**Comment by abe33** [comment]
@Billybobbonnet I understand how annoying it can be. I was expecting Atom and apm to properly honor the engine field in `package.json` that  says that version 4.26.x only works with atom >= 1.13 but it doesn't and it's creating a huge mess for everybody.

**Comment by kaiKitsune** [comment]
thx for the warning
using Atom without minimap
is as starting your day without coffee
it's not the same

**Comment by abe33** [comment]
Hey all, 1.13 was finally released! Which means that you all will be able to use the v4.26.x versions.

**Comment by Billybobbonnet** [comment]
That's a great news. I just updated minimap to the latest version without any trouble 👍

**Comment by uripre** [comment]
Atom 1.13.0
minimap 4.26.6

Not showing up.

**Comment by kaiKitsune** [comment]
works fine for me
atom 1.13.0
minimap 4.26.6
win7x64

**Comment by topjor** [comment]
works fine here too
atom 1.13.0
minimap 4.26.6
linux x64

**Comment by FrankenApps** [comment]
Does not work for mee, too. I am on windows 10 and used `apm install minimap@4.25.7`. It worked but then I updated pigments (another package I have installed) and then it stopped working. Note, that minimap was still the old version as I have not updated it yet. After that I have updated minimap, too. It is still not showing up now. Atom is latest version.
