### ISSUE TITLE
Global scrollPastEnd setting causes minimap to jump when moved.

### ISSUE THREAD

**Issue by CentricStorm** [atom-minimap/minimap#551]
With global scrollPastEnd setting enabled, the editor jumps when scrolling large files with the minimap. The problem was introduced with version 4.26.5 (4.26.4 is unaffected).

**Comment by Sambrosia** [comment]
I also have this issue.

In files with more lines than will fit on screen, dragging the view with the mouse causes it to move much further than it should.

In files with too few lines to fill the screen, the scroll direction is inverted when dragging, but the distance scrolled seems correct.

In all cases if the view isn't at the top of the file, dragging causes erratic behaviour where the view jumps dramatically at the beginning of the drag.
