### ISSUE TITLE
minimap not running

### ISSUE THREAD

**Issue by gkgarry911** [atom-minimap/minimap#552]
I don't know why or what mistake but minimap is not running on my atom text editor. I love minimap but I this is failed after installed the minimap .

plz resolve this problem and notify me at my email address at gkgarry911@gmail.com

**Comment by dreamorosi** [comment]
#550

**Comment by kaiKitsune** [comment]
thx for the warning
using Atom without minimap
is as starting your day without coffee
it's not the same

**Comment by abe33** [comment]
Yep, I suspect the same root cause, happily 1.13 has hitted stable yesterday so I hope people will start upgrading and this issue will occurs less and less
