### ISSUE TITLE
Atom Minimap not working

### ISSUE THREAD

**Issue by MTelot** [atom-minimap/minimap#554]
I installed the package Atom minimap and first time it was working. When I close the whole application and start it again its not working. I though somehow it was disable maybe but when I check it was enabled. However, I disabled it and again enabled it but not working. Check the link bellow. If u directly click on the link it will not work. Copy the link and paste it on url.

[http://i.imgur.com/rraEAuj.png](url)

**Comment by abe33** [comment]
See https://github.com/atom-minimap/minimap/issues/541#issuecomment-263504671
