### ISSUE TITLE
Minimap not showing

### ISSUE THREAD

**Issue by phillipemoreira** [atom-minimap/minimap#556]
Hello, I have just installed ATOM at my windows 7, along with it, I installed the minimap package, it looks ok by checking the settings page, but it just won't show.

**actual result:**

![image](https://cloud.githubusercontent.com/assets/4164091/21575331/d5d19daa-ceef-11e6-8a4f-9e23b78c1dc2.png)

**minimap settings:**

![image](https://cloud.githubusercontent.com/assets/4164091/21575317/6a5a45c2-ceef-11e6-8b62-b46463981eca.png)

**atom version:**

![image](https://cloud.githubusercontent.com/assets/4164091/21575321/960c6722-ceef-11e6-9f74-3dbd777fc6db.png)

**windows version:**

![image](https://cloud.githubusercontent.com/assets/4164091/21575325/b6d21e20-ceef-11e6-9cf3-4072448821af.png)

**Comment by harmanpreet93** [comment]
Uninstall latest minimap and use version 4.25.7 with Atom version 1.12.x

apm install minimap@4.25.7

**Comment by abe33** [comment]
https://github.com/atom-minimap/minimap/issues/541#issuecomment-263504671

**Comment by phillipemoreira** [comment]
ok, thank you.
