### ISSUE TITLE
Cursor-viewfinder misalignment

### ISSUE THREAD

**Issue by WoodyWoodsta** [atom-minimap/minimap#560]
After updating to Atom 1.13.0, the alignment of the viewfinder is not correctly tracking the position of the mouse, as below:

![peek 2017-01-16 08-09](https://cloud.githubusercontent.com/assets/8268040/21972649/9c784f28-dbc3-11e6-9b55-e3af924f77e7.gif)

**Comment by abe33** [comment]
Hi @WoodyWoodsta, I can reproduce that too, I'll look for a patch this evening. Stay tuned!

**Comment by Ben3eeE** [comment]
I see this misalignment when I have the `Scroll Past End` configuration option enabled.
