### ISSUE TITLE
Minimap does not show after I installed Nuclide

### ISSUE THREAD

**Issue by yookoala** [atom-minimap/minimap#561]
After installed [nuclide](https://atom.io/packages/nuclide), I cannot toggle to display minimap at all. Not sure which package caused the issue.

**Comment by yookoala** [comment]
Also reported here: facebook/nuclide#986

**Comment by abe33** [comment]
It'sq because minimap v4.26.x only supports Atom 1.13+n, which is clearly stated in the engine field of the minimap `package.json` file. The solution is either to update Atom to 1.13 or to downgrade minimap to 4.25.x.

**Comment by yookoala** [comment]
Thanks for the explanation :-)
