### ISSUE TITLE
Sudden Jump when scrolling using dragging

### ISSUE THREAD

**Issue by pingshunhuangalex** [atom-minimap/minimap#563]
I'm not sure if I can explain this clearly...

Here is what happened. There is a semi-transparent rectangle on mini-map indicating where I'm on the page. What I usually do is use my mouse to drag that rectangle for more efficient scrolling. However recently, when I start dragging, the rectangle will be suddenly out of position and jump to a new position below my cursor, i.e. when line no. is big, the rectangle will always be below my cursor when dragging, and the difference will increase as it goes on.

Is this an issue that can be fixed? Thanks.

**Comment by shadowRR** [comment]
Your problem is most likely linked to this issue : #560
It basically happens when you have `Scroll Past End` option activated, @abe33 is working on a patch.
