### ISSUE TITLE
Cannot scroll with drag'n'drop when adjustAbsoluteModeHeight is enabled

### ISSUE THREAD

**Issue by kalsan** [atom-minimap/minimap#564]
When absolute mode is enabled but "Adjust Absolute Mode Height" is off, I can neatly scroll through my document by dragging on the Minimap, which is one of my favourite features in the program.

Unfortunately, this feature is disabled when activating the highly useful option "Adjust Absolute Mode Height".

I would much appreciate  the combination of both.

**Comment by jmatsushita** [comment]
Same here!

**Comment by abe33** [comment]
Hi there, it looks to me that it's quite broken, taking a look at it.

**Comment by kalsan** [comment]
Thanks! Looking forward to the next update :-)

**Comment by abe33** [comment]
@kalsan It's available in v4.27.1

**Comment by kalsan** [comment]
Can confirm: It's working perfectly fine. Thanks a lot!
