### ISSUE TITLE
Docs: minimap-autohide plugin has deprecation warnings and no signs of life

### ISSUE THREAD

**Issue by ansballard** [atom-minimap/minimap#569]
Hello! So the only atom package with deprecation warnings in my list is `minimap-autohide`, which hasn't been updated in ~2 years. So I forked it, fixed the warnings, and published to `minimap-autohider`. So I just wanted to see if you all would be willing to swap in my package in the [list of available plugins](https://github.com/atom-minimap/minimap#available-plugins). Basically just replacing https://atom.io/packages/minimap-autohide with https://atom.io/packages/minimap-autohider, since the functionality is the same. Thanks!

**Comment by abe33** [comment]
Ok, thank you for the head up, I'll find some time to update the docs.

**Comment by JMayfield** [comment]
@ansballard this is great, that stupid deprecation warning was bugging the hell out of me. Installed. Love the transform animation as well, great work.
