### ISSUE TITLE
Atom minimap is not working on portable windows platform atom

### ISSUE THREAD

**Issue by aslamanver** [atom-minimap/minimap#579]
Atom minimap is not working on portable windows platform atom, Installed successfully but not even started

**Comment by abe33** [comment]
That's a bit short to start investigating the issue, it's not like I had access to every environments out there. It'd be great if you could provide more details about your configuration and the errors you're seeing in the devtools.

**Comment by kaiKitsune** [comment]
its working fine for me
Atom 1.15.0 [PAF 32/64]
Mimimap: 1.27.1
win7x64

**Comment by aminya** [comment]
Closing as reported working by other users.
