### ISSUE TITLE
package.json needed to be fixed

### ISSUE THREAD

**Issue by NeoZhangTCL** [atom-minimap/minimap#599]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\NieR\\AppData\\Local\\atom\\app-1.16.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\NieR\\AppData\\Local\\atom\\app-1.16.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\NieR\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\NieR\\.atom\\.apmrc" "install" "C:\\Users\\NieR\\AppData\\Local\\Temp\\d-117412-4976-a6sq6y.biw39b2o6r\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! file C:\Users\NieR\.atom\.apm\underscore-plus\1.6.6\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\NieR\.atom\.apm\underscore-plus\1.6.6\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\NieR\AppData\Local\Temp\apm-install-dir-117412-4976-1tatpyn.75zupx2yb9\npm-debug.log

**Comment by mehcode** [comment]
I'm not sure how this is an issue with this package? Your error log looks like it's an issue parsing `underscore-plus` 's package.json

How did you get that error? What command did you run?

**Comment by aminya** [comment]
This issue is too old. I don't think it is relevant now.
