### ISSUE TITLE
Suggestion: Tweaking The Minimap - Making Minimap visible only in the focused pane

### ISSUE THREAD

**Issue by mjharris2407** [atom-minimap/minimap#600]
Switching between display:none / display: block on large files results in a jerky experience as the window repaints the minimap.

Changing this to opacity: 0 / opacity .6 (default) results in a much improved window switching experience.

**Comment by mehcode** [comment]
This should be in a plugin. I would take this feature request to https://github.com/ansballard/minimap-autohider as it already has the clean hide/show logic implemented and could have an option to tweak when it shows.
