### ISSUE TITLE
Can’t find in ionic project (<android>/<app>/build.gradle)

### ISSUE THREAD

**Issue by Heartdeath** [atom-minimap/minimap#602]
I'm trying to add Firebase to my android app builded with ionic, the firebase's documentation https://firebase.google.com/docs/android/setup says to add this line on my root-level build.gradle.

```
buildscript {
    // ...
    dependencies {
        // ...
        classpath 'com.google.gms:google-services:3.1.0'
    }
}
```
and this line in my module Gradle file (usually the app/build.gradle).

```
apply plugin: 'com.android.application'

android {
  // ...
}

dependencies {
  // ...
  compile 'com.google.firebase:firebase-core:10.2.6'

  // Getting a "Could not find" error? Make sure you have
  // the latest Google Repository in the Android SDK manager
}

// ADD THIS AT THE BOTTOM
apply plugin: 'com.google.gms.google-services'
```
But i can't find app/build.gradle in my ionic projet.

![stack](https://cloud.githubusercontent.com/assets/22813795/26586446/771579ea-454f-11e7-9af1-209a1f5a0b3c.PNG)

Where can I find it?

**Comment by ambrosiajun** [comment]
same here

**Comment by niharikaarg** [comment]
Me too

**Comment by bahmadkhaled** [comment]
me too

**Comment by bahmadkhaled** [comment]
did anyone find the solution

**Comment by abdulhafeez** [comment]
Same problem ... no app-level build.gradle

**Comment by raga2560** [comment]
The app level gradle file may be this one.
platforms/android/CordovaLib/build.gradle
