### ISSUE TITLE
Uncaught TypeError: this.getTextEditorElement(...).component.onMouseWheel is not a function

### ISSUE THREAD

**Issue by ajoslin103** [atom-minimap/minimap#606]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.28.2

### Stack Trace

Uncaught TypeError: this.getTextEditorElement(...).component.onMouseWheel is not a function

```
At /Users/ajoslin/.atom/packages/minimap/lib/minimap-element.js:1138

TypeError: this.getTextEditorElement(...).component.onMouseWheel is not a function
    at HTMLElement.relayMousewheelEvent (/packages/minimap/lib/minimap-element.js:1138:45)
    at /packages/minimap/lib/minimap-element.js:492:16)
    at HTMLElement.listener (/packages/minimap/node_modules/atom-utils/lib/mixins/events-delegation.js:108:41)
```

### Commands

```
     -0:36.4.0 intentions:highlight (input.hidden-input)
     -0:36.3.0 sublime-word-navigation:select-to-end-of-word (input.hidden-input)
  2x -0:35.6.0 core:delete (input.hidden-input)
     -0:34.3.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:33.6.0 core:move-down (input.hidden-input)
     -0:32.7.0 core:move-right (input.hidden-input)
     -0:32.4.0 core:paste (input.hidden-input)
     -0:31.8.0 core:move-down (input.hidden-input)
     -0:31.4.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:30.9.0 core:move-right (input.hidden-input)
     -0:30.7.0 core:paste (input.hidden-input)
  8x -0:30.3.0 core:move-down (input.hidden-input)
     -0:26.1.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:25.4.0 core:move-right (input.hidden-input)
     -0:24.6.0 core:paste (input.hidden-input)
     -0:20 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-ternjs 0.18.3 
atom-wrap-in-tag 0.6.0 
auto-update-plus 0.2.0 
bottom-dock 0.4.4 
browse 1.6.1 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
cobalt 0.3.0 
cobalt2-syntax 0.5.1 
ctrl-dir-scroll 0.2.3 
dark-side-of-the-moon-syntax 0.6.26 
eslint-tab-length 0.3.14 
fast-eslint 3.13.0 
fizzy 0.21.0 
hex 0.6.2 
intentions 1.1.2 
kobalt 0.7.1 
kobalt-ui 0.5.1 
linter 2.1.4 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-scss-lint 3.1.0 
linter-ui-default 1.6.1 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
monokai 0.24.0 
multi-cursor 2.1.5 
open-path 0.3.6 
pigments 0.39.1 
satisfy-dependencies 0.3.1 
set-syntax 0.3.2 
shell-it 0.2.1 
simple-drag-drop-text 0.3.4 
split-diff 1.4.1 
sublime 0.5.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
sublime-word-navigation 0.2.0 
sublimify 0.10.0 
tag 0.5.0 
text-manipulation 0.6.0 
todo 0.6.0 
```

**Comment by alexrussell** [comment]
I am getting this too, when using the mouse wheel (scrolling) over the minimap. Presumably this is because the minimap 'proxies' mousewheel events through to the underlying text editor rather then scrolling the minimap itself. And presumably presumably, this is due to a recent (breaking?) change in Atom. I am using the beta version and it recently updated to `1.19.0-beta0`, though I can't see any "breaking changes" messages in any of the recent releases.

**Comment by retrixe** [comment]
@alexrussel except a rewrite of the editor's rendering layer? that's pretty breaking for 1.19.

**Comment by Arcanemagus** [comment]
@retrixe @alexrussell:  The editor rewrite wasn't breaking at all... if you are using the public API. The reason this is broken here is it tied into the private internals which changed considerably.

**Comment by alexrussell** [comment]
Yes I should have made this a little clearer - there was no breaking changes announced to the actual public API for the text editor. Obviously an internal reshuffle shouldn't be a problem as long as its public API is still the same.

I did have a suspicion that the minimap package was using an undocumented feature as `this.getTextEditorElement(...).component` seemed a little unlike a public API.

**Comment by R13e** [comment]
> I am getting this too, when using the mouse wheel (scrolling) over the minimap.

The setting "**Independent Minimap Scroll On Mouse Wheel Events**" wasnt checked in my config and I got this error. After I checked that, the scrolling does not trigger the error anymore. Currently, that's enough.

**Comment by alflanagan** [comment]
Checking that setting did make the problem go away. Afterward, contrary to the documentation for the option, the editor still scrolls with the minimap.
