### ISSUE TITLE
Fatal error: Uncaught Error: Class 'NeverBounce\API\NB_Auth' not found in C:\Users\Thibault\Downloads\neverbounce-client-master\never.php:15

### ISSUE THREAD

**Issue by Heartdeath** [atom-minimap/minimap#609]
Hello, 

I try to use NeverBounce API-PHP.  But when i want to launch my Php file i had this error : 

`Fatal error: Uncaught Error: Class 'NeverBounce\API\NB_Auth' not found in C:\Users\Thibault\Downloads\neverbounce-client-master\never.php:15                                                                                                    Stack trace:
#0 {main}                                                                                                                 thrown in C:\Users\Thibault\Downloads\neverbounce-client-master\never.php on line 15`

Line 15 : `NB_Auth::auth($apisecret, $apikey);`

https://pastebin.com/6ygfbNKq : never.php

The file that contains all the API classes is in the file, where is my class never.php.

**Comment by wyqydsyq** [comment]
@Heartdeath I think you may have posted this issue to the wrong repository. This repo is for the atom minimap package, rather than [NeverBounce](https://github.com/NeverBounce/NeverBounceAPI-PHP)
