### ISSUE TITLE
How can i disable this

### ISSUE THREAD

**Issue by zoutepopcorn** [atom-minimap/minimap#612]
I tried to uninstall disable. Its comming back again...

**Comment by mehcode** [comment]
`apm uninstall minimap` should remove this package if that's your desire. Nothing should be trying to "make it come back". Perhaps you have the `sync-settings` package and have a settings backup where this package is installed? 

Note that the Kite integration is gone and a 3rd-party ( not affiliated with Kite ) has been added to the repository to.
