### ISSUE TITLE
Deprecated selector in `minimap\styles\minimap.less`

### ISSUE THREAD

**Issue by haiyangpan** [atom-minimap/minimap#613]
In `minimap\styles\minimap.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor[with-minimap]::shadow .editor--private,
atom-text-editor[with-minimap] .editor--private` => `atom-text-editor[with-minimap].editor .editor--private,
atom-text-editor[with-minimap] .editor--private`

* `atom-text-editor::shadow atom-text-editor-minimap,
atom-text-editor atom-text-editor-minimap,
html atom-text-editor-minimap` => `atom-text-editor.editor atom-text-editor-minimap,
atom-text-editor atom-text-editor-minimap,
html atom-text-editor-minimap`

* `atom-text-editor::shadow atom-text-editor-minimap:not([stand-alone]),
atom-text-editor atom-text-editor-minimap:not([stand-alone]),
html atom-text-editor-minimap:not([stand-alone])` => `atom-text-editor.editor atom-text-editor-minimap:not([stand-alone]),
atom-text-editor atom-text-editor-minimap:not([stand-alone]),
html atom-text-editor-minimap:not([stand-alone])`

* `atom-text-editor::shadow atom-text-editor-minimap:not([stand-alone]).left,
atom-text-editor atom-text-editor-minimap:not([stand-alone]).left,
html atom-text-editor-minimap:not([stand-alone]).left` => `atom-text-editor.editor atom-text-editor-minimap:not([stand-alone]).syntax--left,
atom-text-editor atom-text-editor-minimap:not([stand-alone]).left,
html atom-text-editor-minimap:not([stand-alone]).left`

* `atom-text-editor::shadow atom-text-editor-minimap.absolute,
atom-text-editor atom-text-editor-minimap.absolute,
html atom-text-editor-minimap.absolute` => `atom-text-editor.editor atom-text-editor-minimap.syntax--absolute,
atom-text-editor atom-text-editor-minimap.absolute,
html atom-text-editor-minimap.absolute`

* `atom-text-editor::shadow atom-text-editor-minimap.absolute.adjust-absolute-height,
atom-text-editor atom-text-editor-minimap.absolute.adjust-absolute-height,
html atom-text-editor-minimap.absolute.adjust-absolute-height` => `atom-text-editor.editor atom-text-editor-minimap.syntax--absolute.adjust-absolute-height,
atom-text-editor atom-text-editor-minimap.absolute.adjust-absolute-height,
html atom-text-editor-minimap.absolute.adjust-absolute-height`

* `atom-text-editor::shadow atom-text-editor-minimap.absolute.adjust-absolute-height::shadow canvas,
atom-text-editor atom-text-editor-minimap.absolute.adjust-absolute-height::shadow canvas,
html atom-text-editor-minimap.absolute.adjust-absolute-height::shadow canvas` => `atom-text-editor.editor atom-text-editor-minimap.syntax--absolute.adjust-absolute-height::shadow canvas,
atom-text-editor atom-text-editor-minimap.absolute.adjust-absolute-height::shadow canvas,
html atom-text-editor-minimap.absolute.adjust-absolute-height::shadow canvas`

* `atom-text-editor::shadow atom-text-editor-minimap.absolute.left,
atom-text-editor atom-text-editor-minimap.absolute.left,
html atom-text-editor-minimap.absolute.left` => `atom-text-editor.editor atom-text-editor-minimap.syntax--absolute.syntax--left,
atom-text-editor atom-text-editor-minimap.absolute.left,
html atom-text-editor-minimap.absolute.left`

* `atom-text-editor::shadow atom-text-editor-minimap.absolute .open-minimap-quick-settings,
atom-text-editor atom-text-editor-minimap.absolute .open-minimap-quick-settings,
html atom-text-editor-minimap.absolute .open-minimap-quick-settings` => `atom-text-editor.editor atom-text-editor-minimap.syntax--absolute .open-minimap-quick-settings,
atom-text-editor atom-text-editor-minimap.absolute .open-minimap-quick-settings,
html atom-text-editor-minimap.absolute .open

**Comment by mehcode** [comment]
@haiyangpan This shouldn't be happening in this package. Do you have any minimap extensions installed?
