### ISSUE TITLE
Updating to “minimap@4.29.1” failed

### ISSUE THREAD

**Issue by Coope-D** [atom-minimap/minimap#619]
Both Atom and the Terminal on Ubuntu will not allow me to update to the latest version of minimap and produces the following error, which I pasted in the "error-message.txt" file. I couldn't locate a "npm-debug.log file" though.

I also tried to reinstall the package but it still produced the same error.

[error-message.txt](https://github.com/atom-minimap/minimap/files/1171387/error-message.txt)

**Comment by aminya** [comment]
This issue is too old. I don't think it is relevant now.
