### ISSUE TITLE
Atom 1.19.0 Minimap settings button broken + always on the right

### ISSUE THREAD

**Issue by r0ckarong** [atom-minimap/minimap#623]
I just updated to Atom 1.19.0 release and the minimap moved to the right side of the window despite explicitly set to be displayed on the left. The gear icon for settings works only when Atom is freshly restarted and then also only once. Once the menu collapses I can click the gear button as much as I want I will not see the options again.

Removing the checkmark in minimap settings directly also does not influence the position, it stays on the right.

There are some major changes in 1.19.0 from how I understand the release notes, is there something I can help to debug this behavior?

**Comment by pjenx** [comment]
+1
after updating to Atom 1.19.0

**Comment by abe33** [comment]
Hey guys, thanks to @DuCorey contribution this should have been fixed in v4.29.4

**Comment by r0ckarong** [comment]
Can confirm, 4.29.4 fixes this for me.
