### ISSUE TITLE
Kite? better change to "Kike"

### ISSUE THREAD

**Issue by noxarivis** [atom-minimap/minimap#630]
https://qz.com/1043614/this-startup-learned-the-hard-way-that-you-do-not-piss-off-open-source-programmers/

your startup is a joke.

**Comment by iamchriswick** [comment]
Whose startup is a joke? 🤔

**Comment by noxarivis** [comment]
@iamchiswick
see the link

**Comment by mehcode** [comment]
Please try and keep issues to bugs or feature requests.
