### ISSUE TITLE
Could you please add border ?

### ISSUE THREAD

**Issue by vv7v7** [atom-minimap/minimap#631]
Dear Developers,
Thank you very much for your plugin ! :+1: :)
It would be awesome if you'd add some border which would be shown. Also ... it could be visible only when text overflows the minimap's container.

Best regards,
V7

**Comment by ethernal** [comment]
I'm not the plugin maintainer so I can't say for sure but shouldn't this be possible with simple CSS? Can you provide a screenshot of what you want to achieve?

**Comment by vv7v7** [comment]
![screenshot_20170909_150743](https://user-images.githubusercontent.com/25136754/30240434-be9bb7d6-9570-11e7-8da5-e1df766a2515.png)

**Comment by mehcode** [comment]
@vv7v7 You can add this by editing `~/.atom/styles.less` ( can be opened with "Application: Open Your Stylesheet" command ).

The following looks _close_ to your screenshot but you can of course tweak it more if you'd like:

```
atom-text-editor-minimap {
  border-left: 1px solid rgba(0, 0, 0, 0.2);
  box-shadow: 0 0 1px 4px rgba(0, 0, 0, 0.1);
}
```

This is an addition that I use locally. It adds a nice littler border around the box.

```
atom-text-editor-minimap .minimap-visible-area {
  border: 1px solid rgba(255, 255, 255, 0.3) !important;
}
```

**Comment by vv7v7** [comment]
Dear mehcode,

Thank you very much really. I'll try.

Best regards,
vv7v7
