### ISSUE TITLE
Drawing issue creating a bit white box?

### ISSUE THREAD

**Issue by AlexanderOMara** [atom-minimap/minimap#635]
Lately I've been noticing some strange drawing errors in Atom apparently related to this plugin.

![issue](https://user-images.githubusercontent.com/1740229/30574017-37b34584-9cc5-11e7-8cb2-085034f2431d.png)

From the developer tools, it appears that `atom-text-editor-minimap` is the element creating this (if I `display: none` that element or disable the plugin, it goes away). Unfortunately, I don't seen any styles being applied to cause this.

To make things stranger, if I click the arrow to expand and close the bottom panel, the drawing issue seems to go away until Atom is restarted.

What might be the cause of this?

**Comment by mehcode** [comment]
I'm fairly sure that this was a rendering glitch in Atom (not this package) related to the version of electron. I think it's fixed in the latest beta. Would you mind trying Atom beta and seeing if you can see the problem there?

**Comment by AlexanderOMara** [comment]
@mehcode It appears you are right. It does not happen in Atom Beta. For reference, is there a specific issue you can link to?

**Comment by mehcode** [comment]
@AlexanderOMara https://github.com/atom/atom/issues/14915
