### ISSUE TITLE
Performance issue : the minimap lag when scrolling

### ISSUE THREAD

**Issue by Nicryc** [atom-minimap/minimap#645]
Hello,
There's a performance issue. When I "grab" the minimap and I scroll by moving my mouse it lags a lot. It's the minimap which lags. It's not smooth at all.

**Comment by skaraman** [comment]
I've recently noticed the minimap impacts scrolling performance if not general performance of the editor also. I've had to disable it as it seems to impact event changing files and brining up settings.

**Comment by aminya** [comment]
Good news: I got access to minimap. I am adding all the performance patches I added to minimap-plus to minimap. So, this is/will be fixed.
