### ISSUE TITLE
Dragging mouse outside range stops scrolling

### ISSUE THREAD

**Issue by multiwebinc** [atom-minimap/minimap#647]
Platform: Ubuntu 17.10 64 bit

Dragging the highlighted area on the minimap vertically up will stop the drag as soon as your mouse reaches the tabs, so when you move your mouse back down (still dragging) it doesn't scroll the minimap anymore. Similarly dragging vertically down or horizontally, as soon as your mouse leaves the Atom window the scrolling stops.

**Comment by UziTech** [comment]
duplicate of #314
