### ISSUE TITLE
very slow to open large text files

### ISSUE THREAD

**Issue by clayms** [atom-minimap/minimap#661]
Opening a 42,000 row 21 column csv file is nearly instantaneous with minimap disabled.  After minimap is enabled opening this same file can take up to 10 seconds to load.  Nothing else is changed in the session.  I have repeated this many times.

Windows 10
Atom 1.25.6 x64
minimap 4.29.8

**Comment by C-Bouthoorn** [comment]
42000 rows are quite a lot, but I even experience this with files of 200 to 400 lines. Disabling minimap made it much, MUCH smoother. CPU-usage went from 20% to 1% by disabling minimap. I have no idea why.

Arch 4.16.13-1
Atom 1.27.2
minimap 4.29.8

**Comment by HaritzGarai** [comment]
This also happens to me. I do not have the same problem with other editors (sublime text or vscode).

Ubuntu 18.04
Atom 1.32.0
minimap 4.29.9

**Comment by aminya** [comment]
Good news: I got access to minimap. I am adding all the performance patches I added to minimap-plus to minimap. So, this is/will be fixed.
