### ISSUE TITLE
Wont open for all files

### ISSUE THREAD

**Issue by TrebleStick** [atom-minimap/minimap#665]
So i'm using latest versions on minmap & atom and the minmap will only open up for some files. There doesn't seem to me any specific file type it doesn't like but it will leave an empty gap at the side of the editor when it doesn't load. see images. Any ideas?
![image](https://user-images.githubusercontent.com/25103057/39760527-6eb9f67c-52cd-11e8-84ee-a3a4272dcd45.png)

**Comment by UziTech** [comment]
Is this still an issue with the latest version?

**Comment by aminya** [comment]
Closing due to no answer
