### ISSUE TITLE
Atom Beta leaving space on right side for MiniMap that is on the left

### ISSUE THREAD

**Issue by JoshMerlino** [atom-minimap/minimap#668]
![issue](https://user-images.githubusercontent.com/31785395/42007481-5acbf144-7a4e-11e8-9635-a0ba181b8f1a.png)

Atom is leaving space on the right side for the mini map even though its set to the left side. I'm pretty sure that its some conflict within Atom Beta because I never remember seeing the space before switching to the Beta channel.

**Comment by DallasO** [comment]
I have this same issue, except my minimap is on the right. The mini map disappears, that empty space stays on the right, and the file tree gets pushed off my screen so I can only see half of it.

**Comment by JoshMerlino** [comment]
This issue has been resolved within the past year so im closing it.
