### ISSUE TITLE
Minimap hides text in tabs

### ISSUE THREAD

**Issue by shawnpyle** [atom-minimap/minimap#669]
After the recent update to Atom 1.28.1, minimap seems to cause some problems displaying text in tabs. 
![image](https://user-images.githubusercontent.com/48266/42695340-179b8812-8683-11e8-99aa-11bf0bc80875.png)

If I open the preferences or about tabs, I see the text again. 
![image](https://user-images.githubusercontent.com/48266/42695401-45363222-8683-11e8-98e8-ad2ae63393a9.png)

Disabling the minimap package allows the text to show again.

$ uname -a
Darwin shawn-desktop.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199

$ atom -v
Atom    : 1.28.1
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3

$ apm list --installed --bare
atom-beautify@0.32.5
atom-ide-ui@0.12.0
atom-mermaid@3.3.1
auto-update-packages@1.0.1
busy-signal@1.4.3
docblockr@0.13.7
editorconfig@2.2.2
file-icons@2.1.22
git-blame@1.7.0
goto-definition@1.3.4
highlight-selected@0.14.0
hyperclick@0.1.5
intentions@1.1.5
language-applescript@0.3.0
language-haml@0.31.1
language-powershell@4.0.1
language-r@0.4.2
line-diff-details-plus@1.9.1
linter@2.2.0
linter-phpmd@2.0.0
linter-ui-default@1.7.1
markdown-preview-enhanced@0.15.6
maximize-panes@0.2.0
minimap@4.29.8
open-unsupported-files@1.0.20
pigments@0.40.2
print-atom@0.1.1
project-manager@3.3.6
ssh-config@0.13.0
todo-show@2.3.0
xml-formatter@0.11.0

**Comment by UziTech** [comment]
Is this still an issue with the latest version?

**Comment by shawnpyle** [comment]
@UziTech I've moved on to use VSCode. Closing this for now.
