### ISSUE TITLE
Slider moves into text area on horizontal scroll

### ISSUE THREAD

**Issue by bbdaniels** [atom-minimap/minimap#676]
When scrolling horizontally, especially when code is very wide, the slider moves into the editor area. Screenshot:

<img width="532" alt="screenshot 2018-10-19 11 52 21" src="https://user-images.githubusercontent.com/1459122/47229363-9056de00-d395-11e8-88e5-58c4316a2c34.png">

**Comment by UziTech** [comment]
is this still an issue? what version of Atom and minimap?

**Comment by bbdaniels** [comment]
No, this appears to be resolved in Minimap 4.35.2. Thanks!
