### ISSUE TITLE
horizontal scrolling moves view to start of file (when softwrap is off)

### ISSUE THREAD

**Issue by imLew** [atom-minimap/minimap#679]
I just installed minimap and found that anytime the view in a file moves in the horizontal direction, whether it is caused by typing or by using the horizontal scrollbar, the view will move to the top of the file.

enabling softwrap fixes this issue.

**Comment by PCelestia** [comment]
can confirm this still happens

**Comment by aminya** [comment]
Hey everyone. Minimap is abandoned. Please post your issues in minimap-plus:
https://atom.io/packages/minimap-plus
