### ISSUE TITLE
Unexpected minimap overlay

### ISSUE THREAD

**Issue by kawa-marcin** [atom-minimap/minimap#688]
Minimap overlays some bright element on top, decreasing the readability.
I have tried to override the styles as per documentation but even when new background colour is defined, this white overlay is still on top of the new background.

Changing the `text opacity` in the config did not help.

**Atom Version**: 1.35.1 x64
**Minimap Version**: 4.29.9
**System**: Windows 10

![screenshot-min](https://user-images.githubusercontent.com/4525682/55293851-e2933500-53f2-11e9-8ec4-a99c90eb2722.png)

**Comment by UziTech** [comment]
see #640
