### ISSUE TITLE
Mini-map will not display code in .hpp format.

### ISSUE THREAD

**Issue by 56curious** [atom-minimap/minimap#690]
Hello, I use the file format .hpp and the minimap wont display the code, however the lens will (Lens plugin)
I have tried removing all plugins to see if one of them causes the issue, but it still didn't display.

![image](https://user-images.githubusercontent.com/41159450/57182752-dd665180-6e9a-11e9-93c9-a9b54631aac3.png)

**Comment by aminya** [comment]
I can't reproduce this. Please try the latest version
