### ISSUE TITLE
Minimap has confilicts with other packages

### ISSUE THREAD

**Issue by maky-hnou** [atom-minimap/minimap#693]
- **OS:** Ubuntu 18.04
- **Editor:** Atom 1.43.0  
- **Node:** v10.11.0  
- **Minimap:** 4.29.9  
- **Minimap setting:** all set to default, none is changed.

  
I opened Atom, everything is working as usual. I got a notification that some packages need to be updated, I updated the packages and restarted Atom, but I was surprised that minimap does not work anymore!  
I uninstalled minimap and reinstalled it again, uninstalled Atom, removed the configs, and installed atom and minimap all along with with the other packages. However minimap still not working.  
I uninstalled [docblock-python](https://github.com/spadarian/docblock-python), minimap is showing again!   

I thought that the last update of docblock-python had messed something, so I reported the issue to its owner. However it seems that the problems comes from minimap.  

The problem was solved, thanks to [@Spadarian](https://github.com/spadarian), after I changed the line 391 from the function `initSubscriptions` in the file `minimap/lib/main.js`:  
from: `let minimapElement = atom.views.getView(minimap)`  
to: `let minimapElement = this.minimapViewProvider(minimap)`  
More details in [this link](https://github.com/spadarian/docblock-python/issues/43).  

Please fix this conflict.

**Comment by aminya** [comment]
We now use the minimapViewProvider so there must not be a conflict anymore.

**Comment by maky-hnou** [comment]
Thank you for your support.
Now there is no conflict anymore.
