### ISSUE TITLE
⚠️ ⚠️ Notice: Minimap-plus is an active fork ⚠️ ⚠️ 

### ISSUE THREAD

**Issue by aminya** [atom-minimap/minimap#700]
A community fork of the minimap is now available here:
https://atom.io/packages/minimap-plus

Feel free to check out the repository:
https://github.com/atom-ide-community/minimap-plus

~~Is the minimap repository dead? If so, you should transfer it to someone that continues developing and merges the pull requests.~~

**Comment by aminya** [comment]
@abe33 If you give me access, we can let the current users benefit from the improvement. I can register the fork under the same name. Since I emailed you personally, and I did not get a response I created this fork until I get some message form you.

**Comment by utkarshgupta137** [comment]
@aminya Can you fork https://github.com/atom-minimap/minimap-git-diff/pull/31?

**Comment by aminya** [comment]
Yes, I can do that!

**Comment by mehcode** [comment]
I can't give you access but I can at least pin this issue so its easier for people to find.

**Comment by aminya** [comment]
@mehcode Do you have write access to minimap? I emailed you before, but I don't think you received it.

**Comment by mehcode** [comment]
I do. But I do not have access to give others write access nor do I have time to do much with this project.

**Comment by aminya** [comment]
@mehcode I have only one idea to inform others about the move. If I make a PR that gives a message about the deprecation of this package and installs/recommends the new fork, would you be able to merge it?

**Comment by mehcode** [comment]
You'd have a much better reach getting a change to https://github.com/atom/atom/blob/master/script/deprecated-packages.json merged.

**Comment by aminya** [comment]
Good news, finally we got access to this repo. so I am closing this. I am bringing all the patches from minimap-plus
