### ISSUE TITLE
minimap run too slow

### ISSUE THREAD

**Issue by yuanyuan12543** [atom-minimap/minimap#707]
Hi, I have a minimap running too slow, 30 days still not done.

Could you please help me check if my script is Okay? 
[minimap.txt](https://github.com/atom-minimap/minimap/files/5219483/minimap.txt)

Do you have any suggestions to speed up the program?

Thanks!

Junli

**Comment by aminya** [comment]
Hey everyone. Minimap is abandoned. Please post your issues in minimap-plus:
https://atom.io/packages/minimap-plus

**Comment by aminya** [comment]
Good news: I got access to minimap. I am adding all the performance patches I added to minimap-plus to minimap.

So this is/will be fixed.
