### ISSUE TITLE
Overlayed minimaps

### ISSUE THREAD

**Issue by EricMaGo** [atom-minimap/minimap#724]
With the last update two maps appear one on top of the other, but only one moves when scrolling

![bug](https://user-images.githubusercontent.com/19272495/100205300-3a09e100-2f05-11eb-90b1-33f78da3edc0.gif)

**Comment by nemesisridiculii** [comment]
I have this same issue

![image](https://user-images.githubusercontent.com/25368182/100235591-9ddadc80-2efa-11eb-9383-b65820fe95f6.png)

**Comment by UziTech** [comment]
Can you provide versions for Atom and OS?

**Comment by UziTech** [comment]
Does it still appear after restarting Atom? It could be a case where the old one is not removed on deactivate.

**Comment by EricMaGo** [comment]
Already tried that (first thing that I tried), keep happening. Also tried reinstalling the package
Os is Ubuntu Focal Fossa and I'm using Atom 1.53.0 with minimap 4.35.2

**Comment by nemesisridiculii** [comment]
I have also tried restarting atom, and tried toggling all of the options in settings. I also disabled the minimap-selection plugin, but none of this helped. I'm running Atom version 1.53.0 x64 on Ubuntu 20.10 (Groovy Gorilla) x64

**Comment by aminya** [comment]
Could you give the list minimap plugins and a screenshot of your minimap settings?

**Comment by TizianoGC** [comment]
I have the same problem with Minimap 4.35.2 after a fresh installation of Atom from the Ubuntu software centre, without adding the Atom official repositories. Restarting Atom and logging out from Ubuntu didn't solve this issue, could you please fix it? Below you can find the OS and atom versions:
**OS**
Ubuntu 20.04
**Atom**
Atom 1.53.0 x64
Electron 6.1.12
Chrome 76.0.3809.146
Node v12.4.0

Minimap 4.35.2

Thank you!

**Comment by aminya** [comment]
We can't fix the issue without being able to reproduce it. Could you give more information?
The best way to do so is to upload your ~/atom/config.cson

**Comment by TizianoGC** [comment]
Yes, of course. Please see the attached file (I added the txt extension to upload it).
[config.cson.txt](https://github.com/atom-minimap/minimap/files/5606993/config.cson.txt)

**Comment by aminya** [comment]
@TizianoGC is this the situation that it happens? The config shows that you have disabled minimap! Please reproduce the error, and then close Atom, and finally upload the file.

**Comment by TizianoGC** [comment]
Sorry about that. Yes, the error is still present, here there is the config file with minimap enabled:
[config.cson.txt](https://github.com/atom-minimap/minimap/files/5607032/config.cson.txt)

I just noticed a new version of Minimap (4.35.3), shall I try it now and check if the error is still occurring?

**Comment by aminya** [comment]
Thanks! 

> I just noticed a new version of Minimap (4.35.3), shall I try it now and check if the error is still occurring?

Yes, please!

**Comment by TizianoGC** [comment]
Unfortunately it is still happening.

**Comment by aminya** [comment]
@TizianoGC Are you familiar with dev tools? If so, execute the following command (CTRL+Shift+P and search for the command) 
```
Window: Toggle Dev Tools
```

Then try to inspect the overlayed minimaps, then give a screenshot of the HTML.

![image](https://user-images.githubusercontent.com/16418197/100435707-ef52ab00-3063-11eb-8031-88ec0df29995.png)

You see the minimap element here:
![image](https://user-images.githubusercontent.com/16418197/100435789-0d201000-3064-11eb-97df-26f4690362f2.png)

You can for example delete it
![image](https://user-images.githubusercontent.com/16418197/100435793-0e513d00-3064-11eb-8119-c6264cee1068.png)

**Comment by TizianoGC** [comment]
Deleting the element as you suggested removes entirely the minimap from the editor and deleting the canvasses either remove the minimap or change nothing.
I don't know if it is useful, but selecting the minimap in the editor highlights the 3rd canvas (where `== $0` is) instead of the `atom-text-editor-minimap` as in your example: ![example1](https://user-images.githubusercontent.com/11617713/100438536-2e9bee80-309a-11eb-9680-63f02d9dc467.png)

**Comment by MetRonnie** [comment]
I can reproduce with
- Red Hat Enterprise Linux 7
- Atom 1.53.0 x64
- minimap 4.35.3

**Comment by aminya** [comment]
> Deleting the element as you suggested removes entirely the minimap from the editor and deleting the canvasses either removes the minimap or changes nothing.
> I don't know if it is useful, but selecting the minimap in the editor highlights the 3rd canvas (where `== $0` is) instead of the `atom-text-editor-minimap` as in your example: 

@TizianoGC I can see here that you only have one minimap element! Why does it show two then? Could you open a single file that reproduces the issue and send the screenshot of HTML?

**Comment by aminya** [comment]
Could you try installing the previous versions one by one until the issue gets fixed? I want to know which version is causing this issue.

I know this is a lot, but you probably want to try a few of them until you want which one is causing the issue.
```
# After installation of each you need to restart Atom
apm install minimap@4.35.2
apm install minimap@4.35.1
apm install minimap@4.35.0
apm install minimap@4.34.0
apm install minimap@4.33.0
apm install minimap@4.32.0
apm install minimap@4.31.1
apm install minimap@4.31.0
apm install minimap@4.30.2
apm install minimap@4.30.1
apm install minimap@4.30.0
apm install minimap@4.29.9
```
https://github.com/atom-minimap/minimap/releases

**Comment by TizianoGC** [comment]
> > Deleting the element as you suggested removes entirely the minimap from the editor and deleting the canvasses either removes the minimap or changes nothing.
> > I don't know if it is useful, but selecting the minimap in the editor highlights the 3rd canvas (where `== $0` is) instead of the `atom-text-editor-minimap` as in your example:
> 
> @TizianoGC I can see here that you only have one minimap element! Why does it show two then? Could you open a single file that reproduces the issue and send the screenshot of HTML?

Yes, here it is: ![minimap1](https://user-images.githubusercontent.com/11617713/100513510-1c3bb680-3167-11eb-8bb9-6c6c74e7107c.png)

**Comment by TizianoGC** [comment]
> Could you try installing the previous versions one by one until the issue gets fixed? I want to know which version is causing this issue.
> 
> I know this is a lot, but you probably want to try a few of them until you find the one that is causing the issue. After installation of each, you need to restart Atom (CTRL+Shift+F5).
> 
> ```
> apm install minimap@4.35.2
> apm install minimap@4.35.1
> apm install minimap@4.35.0
> apm install minimap@4.34.0
> apm install minimap@4.33.0
> apm install minimap@4.32.0
> apm install minimap@4.31.1
> apm install minimap@4.31.0
> apm install minimap@4.30.2
> apm install minimap@4.30.1
> apm install minimap@4.30.0
> apm install minimap@4.29.9  # This definitely works
> ```
> 
> https://github.com/atom-minimap/minimap/releases


Minimap works fine from 4.29.9 until 4.32.0, then from version 4.33.0 doesn't work correctly any more.

**Comment by keithnewman** [comment]
I can confirm I have the same issue as @TizianoGC and @EricMaGo.

I'm running the same Ubuntu 20.04 LTS / Atom 1.53.0 x64 / Minimap v4.35.4 set-up.
Like @TizianoGC, I also found that v4.32.0 is the last working version and v4.33.0 doesn't work. Fortunately, there weren't many changes between these versions, so it's quick to diagnose that the problem is triggered by the change to [line 17 of canvas-layer.js](https://github.com/atom-minimap/minimap/blob/e40f83358d74fc7f09eb212b3264ed63316e69c2/lib/canvas-layer.js#L17)

If I set `desynchronized` to `false` on line 17 of canvas-layer.js in my installation of Minimap v4.35.4 and restart Atom, the issue no longer happens. i.e.

```diff
    /**
     * The onscreen canvas context.
     * @type {CanvasRenderingContext2D}
     */
-    this.context = this.canvas.getContext('2d', { desynchronized: true })
+    this.context = this.canvas.getContext('2d', { desynchronized: false })
```

But I don't know why this only seems to affect certain platforms/installations.

**Comment by aminya** [comment]
This seems to be specific to Ubuntu. desynchronized canvas are more performant than traditional canvas. I think we should fall back to the traditional canvas for the operating systems that do not support low-latency rendering. 

https://developers.google.com/web/updates/2019/05/desynchronized

Based on this image, it seems Ubuntu does not support it. 
![image](https://user-images.githubusercontent.com/16418197/100692630-db9f9100-3350-11eb-8ace-c251cee7056b.png)
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext

**Comment by aminya** [comment]
I have disabled desynchronized for Linux. If you have Linux, please try the latest version once it is released. 

If you are interested in contributing, please see if setting lowLatency to true also causes the same problem

**Comment by keithnewman** [comment]
Setting `lowLatency: true` in place of `desynchronized: true` in Minimap v4.35.4 does not cause the original problem with overlayed minimaps. However, I don't have a benchmark/test case to see if `lowLatency` is actually providing the low-latency benefits that are supposed to be given by the desynchronized canvas, or if the setting is simply being ignored. It *feels* a tiny bit more responsive when scrolling rapidly, but that could be a placebo effect.

**Comment by jdashg** [comment]
Chromium does not currently recognize "lowLatency" as a key: https://source.chromium.org/chromium/chromium/src/+/master:out/win-Debug/gen/third_party/blink/renderer/bindings/modules/v8/v8_canvas_context_creation_attributes_module.cc;drc=d81c5852498699fe3cd812e78d31c77c28e29281;bpv=1;bpt=1;l=22?q=preserveDrawingBuffer&ss=chromium

You can check if an attribute is recognized by checking for its presence as a key in the object returned from getContextAttributes().

**Comment by aminya** [comment]
You should feel the difference when you set redrawDelay to 0. When you type in a large file, minimap updates should not slow down your typing. 

Originally, I wanted to decrease redrawDelay, but I avoided that as I did not know if low latency canvas are supported on all operating systems. Minimap updates are not anything critical IMO, and so I prefer it not to be hard real time. The text editor itself is much more important, and that's where it should feel fast and smooth. 

![image](https://user-images.githubusercontent.com/16418197/100710540-7ca04300-3375-11eb-8bab-0f3b327f8b19.png)

**Comment by TizianoGC** [comment]
Many thanks for the support and for fixing this issue :)
