### ISSUE TITLE
Update from v4.29.9 to v4.35.2 on Mac fails with this error

### ISSUE THREAD

**Issue by lukerobertson417** [atom-minimap/minimap#725]
Updating to “minimap@4.35.2” failed.Hide output…

npm ERR! Invalid dependency type requested: alias

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/luke.robertson/.atom/.apm/_logs/2020-11-25T17_46_12_818Z-debug.log

**Comment by UziTech** [comment]
a quick google search brings up this [answer](https://stackoverflow.com/a/58288309/806777).

basically you have to update atom or npm

**Comment by lukerobertson417** [comment]
You are 100% correct. I deserve that.

Thanks, it worked after I updated atom.

**Comment by aminya** [comment]
I assumed that people who receive notifications for updating packages also received notification for updating Atom itself. Isn't that the case?

We can not use aliases to support old Atom versions.

**Comment by lukerobertson417** [comment]
I think that because the Atom app upgrade itself was broken on my machine, it wasn't notifying me to upgrade Atom (and thus it was causing successive failures for Atom plugins as well). Once I managed to fix the problem with Atom not updating, it resolved everything.

**Comment by UziTech** [comment]
> We can remove aliases to support old Atom versions.

I already did that but as a chore so no new release was created. 0b6307316838cc6b8577ffd559deac65bb916d9a

We can just include it in the next release.

**Comment by aminya** [comment]
Thanks!
