### ISSUE TITLE
Suggestion: Rename "Auto Toggle" to "Show Minimap on Atom Start"

### ISSUE THREAD

**Issue by ThomasLandauer** [atom-minimap/minimap#727]
"toggle" means "switch". So "auto toggle" sounds like the minimap is shown/hidden somehow automatically - what in fact [minimap-autohider](minimap-autohider) is supposed to do.

Suggestion: Rename this option in the Settings to "Show Minimap on Atom Start"

**Comment by UziTech** [comment]
Can you create a PR with this change?
