### ISSUE TITLE
atom crash after upgrade to v4.35.5

### ISSUE THREAD

**Issue by mohamed-alashry** [atom-minimap/minimap#731]
atom crash if i closed git right sidebar after upgrade to minimap v4.35.5.
i disabled minimap package and atom working successfully.

atom v1.44.0
minimap v4.35.5
os windows 7

**Comment by UziTech** [comment]
atom version? os version? any other information that might be helpful?

**Comment by UziTech** [comment]
Can you provide minimap config and plugin list as well?

**Comment by mjpalestina** [comment]
Same issue after update. Crashes when enabled. 
Atom: 1.48.0
minimap v4.35.5
OS: Windows 10 v20H2

Config:
  minimap:
    plugins:
      "split-diff": true
      "split-diffDecorationsZIndex": 0

Plugs:
Built-in Atom Packages (93)
├── atom-dark-syntax@0.29.1
├── atom-dark-ui@0.53.3
├── atom-light-syntax@0.29.1
├── atom-light-ui@0.46.3
├── base16-tomorrow-dark-theme@1.6.0
├── base16-tomorrow-light-theme@1.6.0
├── one-dark-ui@1.12.5
├── one-light-ui@1.12.5
├── one-dark-syntax@1.8.4
├── one-light-syntax@1.8.4
├── solarized-dark-syntax@1.3.0
├── solarized-light-syntax@1.3.0
├── about@1.9.1
├── archive-view@0.65.2
├── autocomplete-atom-api@0.10.7
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.8
├── autocomplete-plus@2.42.3
├── autocomplete-snippets@1.12.1
├── autoflow@0.29.4
├── autosave@0.24.6
├── background-tips@0.28.0
├── bookmarks@0.46.0
├── bracket-matcher@0.91.2
├── command-palette@0.43.5
├── dalek@0.2.2
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.9
├── exception-reporting@0.43.1
├── find-and-replace@0.219.6
├── fuzzy-finder@1.14.3
├── github@0.35.0
├── git-diff@1.3.9
├── go-to-line@0.33.0
├── grammar-selector@0.50.1
├── image-view@0.64.0
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.39.0
├── line-ending-selector@0.7.7
├── link@0.31.6
├── markdown-preview@0.160.2
├── metrics@1.8.1
├── notifications@0.71.0
├── open-on-github@1.3.2
├── package-generator@1.3.0
├── settings-view@0.261.6
├── snippets@1.5.1
├── spell-check@0.76.1
├── status-bar@1.8.17
├── styleguide@0.49.12
├── symbols-view@0.118.4
├── tabs@0.110.0
├── timecop@0.36.2
├── tree-view@0.228.1
├── update-package-dependencies@0.13.1
├── welcome@0.36.9
├── whitespace@0.37.7
├── wrap-guide@0.41.0
├── language-c@0.60.19
├── language-clojure@0.22.8
├── language-coffee-script@0.50.0
├── language-csharp@1.1.0
├── language-css@0.44.4
├── language-gfm@0.90.8
├── language-git@0.19.1
├── language-go@0.47.2
├── language-html@0.53.1
├── language-hyperlink@0.17.1
├── language-java@0.32.0
├── language-javascript@0.134.1
├── language-json@1.0.5
├── language-less@0.34.3
├── language-make@0.23.0
├── language-mustache@0.14.5
├── language-objective-c@0.16.0
├── language-perl@0.38.1
├── language-php@0.44.7
├── language-property-list@0.9.1
├── language-python@0.53.5
├── language-ruby@0.72.23
├── language-ruby-on-rails@0.25.3
├── language-rust-bundled@0.1.0
├── language-sass@0.62.1
├── language-shellscript@0.28.2
├── language-source@0.9.0
├── language-sql@0.25.10
├── language-text@0.7.4
├── language-todo@0.29.4
├── language-toml@0.20.0
├── language-typescript@0.6.3
├── language-xml@0.35.3
└── language-yaml@0.32.0

Community Packages (42) C:\Users\user\.atom\packages
├── ascii-tree@1.2.1 (disabled)
├── atom-beautify@0.33.4
├── atom-css-clean@2.24.1
├── atom-handlebars@1.3.0 (disabled)
├── atom-ide-ui@0.13.0
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── atom-typescript@14.1.2 (disabled)
├── autocomplete-paths (disabled)
├── change-case@0.6.5
├── color-picker@2.3.0
├── compare-files@0.8.1
├── css-declaration-sorter@2.0.0
├── dracula-syntax@3.0.2
├── emmet@2.4.3
├── file-icons@2.1.44
├── git-blame@1.8.0
├── git-plus@8.7.1 (disabled)
├── git-time-machine@2.1.0
├── highlight-selected@0.17.0
├── html-to-css@0.2.2
├── jekyll@2.1.0
├── language-autohotkey2@1.0.1 (disabled)
├── language-babel@2.85.0
├── language-hugo@0.5.1 (disabled)
├── language-javascript-jsx@0.3.7
├── language-renpy@2.5.0 (disabled)
├── markdown-preview-plus@4.8.4 (disabled)
├── markdown-writer@2.11.11 (disabled)
├── minimap@4.35.5
├── minimap-split-diff@0.3.7 (disabled)
├── pigments@0.40.6
├── platformio-ide-terminal@2.10.0 (disabled)
├── scroll-sync@0.2.4
├── smart-quotes-plus@3.0.1
├── sort-lines@0.19.0
├── split-diff@1.6.1
├── sync-settings@5.0.9
├── tool-bar@1.4.2
├── tool-bar-main@0.0.12
├── tool-bar-markdown-writer@0.5.1 (disabled)
└── tree-view-sort@0.12.1

**Comment by aminya** [comment]
Could you try the previous version and see if it solves the issue
```
apm install minimap@4.35.4
```

**Comment by mjpalestina** [comment]
Rolled back to version 4.35.4 as requested. Enabled and Atom worked as expected.

**Comment by aminya** [comment]
A new version will be released soon. Let us know if it solves the issue.

**Comment by mjpalestina** [comment]
Installed update 4.35.6. Atom is working as expected. Thank you.
