### ISSUE TITLE
Amount of updates

### ISSUE THREAD

**Issue by m1ga** [atom-minimap/minimap#767]
**First of all:** I love updates and seeing that a package is still active in development :+1: 

But could you perhaps merge multiple smaller updates into one? Every time I start my Atom it has a new Minimap package update notification :smile:

**Comment by aminya** [comment]
Thanks for the comment. We use an automatic release system, and every change on master triggers a release. Minimap has gone under huge performance optimizations, refactoring. Also, recently a few bugs slipped into the codebase that had to be fixed. 

From now on, I expect the number of releases to reduce as there will not be many changes. 

If there were new changes, I will try to merge them into one large PR, or maybe disable automatic releasing.

**Comment by m1ga** [comment]
Thank you for the quick feedback and your work on the module :+1:

**Comment by UziTech** [comment]
Also @aminya it would be nice to get some tests written for PRs that fix something so it doesn't happen again.

We should also figure out a way to run tests for plugins with every PR because a few of the latest releases have broken some of the plugins.

**Comment by aminya** [comment]
I always add new tests or change them if I add a feature or change something.

I like the idea of running the tests for plugins. Although I test everything locally, it is good to make it automatic.

**Comment by aminya** [comment]
I will close this as I explained the reasons.
