### ISSUE TITLE
Uncaught TypeError: Cannot read property 'DecorationManagement' of null is back with a friend

### ISSUE THREAD

**Issue by KalAvroniev** [atom-minimap/minimap#770]
See last comment added to closed issue -  https://github.com/atom-minimap/minimap/issues/766

And previous close issue for the other error - https://github.com/atom-minimap/minimap/issues/572

**Comment by aminya** [comment]
I spent a lot of time trying to find the reason, but I don't know why this happens. I will add some naive null checks for now.

**Comment by aminya** [comment]
Opened the old issue #766
