### ISSUE TITLE
Editor tab ‘blends’ into minimap if it is on left and multiple panes are open

### ISSUE THREAD

**Issue by bassamanator** [atom-minimap/minimap#782]
I prefer my minimap on the left but this is what happens to it:
![image](https://user-images.githubusercontent.com/61985779/107173608-2d3e4a80-6996-11eb-9d08-9ffab2f39f10.png)

It doesn't always happen, it just happens sometimes, specially when having multiple panes open.

When I move the minimap to the right side of the code editor window (which I don't like), the problem goes away.

1.54.0
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.7-3-MANJARO
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: Radeon RX 580 Series

**Comment by UziTech** [comment]
I am unable to reproduce this. Is there any way you can get more specific about when it happens?

**Comment by bassamanator** [comment]
I wish I could tell you. I cannot reproduce this problem myself but it happens all the time.

To escape this issue, I had switched the minimap to the right side of the editor. I've switched it back to the left (the setting under which this problem occurs) and I'm going to wait for it to happen then I'll report back here with more details.

At this point, as far as I can tell, the necessary conditions are:
-minimap on the left.
-2 editor panes at least.
-resizing the panes. I use a package called hey-pane that enlarges the current pane for you, just the way you would manually. hey-pane itself is not a necessary condition because the problem occurs without the use of hey-pane as well.

**Comment by UziTech** [comment]
Ah, resizing is the key. It looks like there is some issue with making the editor the correct size while resizing.

![minimap-resize](https://user-images.githubusercontent.com/97994/107273717-0d01a080-6a15-11eb-84a5-8126f2dc9312.gif)

**Comment by aminya** [comment]
I think we should issue a notification about the issue when multiple panes are open and minimap is on left, and suggest moving the Minimap to the right if they want to avoid this issue.

**Comment by bassamanator** [comment]
Ah, so I'm stuck with minimap on the right :/

In any case, I can't live without this package. Keep up the good work guys! :+1:

**Comment by UziTech** [comment]
I'll take a look at this tonight and see if there is an easy fix.

**Comment by UziTech** [comment]
I see the problem is that minimap calculates the width and tries to move the editor to the right by that width. The problem is when there are multiple minimaps they might each have different widths but it has to choose one.

This seems like it can be solved by calculating each visible minimap on resize and compensating editors differently. I'll work on this in the next few days.

**Comment by UziTech** [comment]
Actually that was easier than I thought. #783 should fix this. I just need to test it a little more to make sure it doesn't break anything else.

**Comment by bassamanator** [comment]
I'd love to help in testing if you need.

**Comment by UziTech** [comment]
Sure, You can install the branch https://github.com/UziTech/minimap/tree/left-width to test it out

1. uninstall minimap
2. clone https://github.com/UziTech/minimap/tree/left-width
3. run `npm i` in the cloned folder
4. run `apm link`
