### ISSUE TITLE
color issues in Electron 9

### ISSUE THREAD

**Issue by UziTech** [atom-minimap/minimap#786]
Since updating to Atom v1.56.0-beta0 there have been some quite a few color issues. I'm guessing it is because v1.56.0-beta0 comes with Electron v9.4.4

![minimap-resize](https://user-images.githubusercontent.com/97994/110886222-f10c4b80-82ad-11eb-9d28-d998ea6b4c0a.gif)

**Comment by aminya** [comment]
I knew about this issue. I hoped I could do something else instead of disabling unsynchronized canvas, but I guess we have no choice.
