### ISSUE TITLE
Minimap Toggle not run: Minimap not appear in Atom.

### ISSUE THREAD

**Issue by fjsrey** [atom-minimap/minimap#801]
I have uninstalled and installed Minimap after an Atom crash, and now Minimap does not appear in the editor.

After the Atom crashed, Minimap did not appear again.

Any ideas?

**Comment by UziTech** [comment]
What OS?
What version of Atom?
If you run `Minimap: Toggle` from the command palette does it show up?

**Comment by fjsrey** [comment]
Hi!

OS: Microsoft Windows [Versión 10.0.18362.1256]
ATOM: 1.58.0  - 64bit
Minimap don't appear when I click on the Toggle option.

**Comment by UziTech** [comment]
I have the same versions and it works just fine so it must be something to do with your configuration or another package. I know minimap has had issues with the zen package.

**Comment by fjsrey** [comment]
I do uninstall all Community Packages and now minimap appears.

Thanks.

**Comment by aminya** [comment]
> I do uninstall all Community Packages and now minimap appears.
> 
> Thanks.

You have probably used a "minimap" hider package. Don't.
