### ISSUE TITLE
Idea: Display bookmarks / symbol names directly in the minimap

### ISSUE THREAD

**Issue by p-e-w** [atom-minimap/minimap#89]
Being pointed to https://github.com/fundon/atom-minimap/issues/69 from another issue (https://github.com/fundon/atom-minimap/issues/88) I came across the really cool idea of using ASCII art to render headings in the minimap for the first time:

![Screenshot](https://cloud.githubusercontent.com/assets/464121/2915284/243288dc-d6ab-11e3-8d56-8b8fb82bea2d.png)

This makes me wonder, wouldn't it be great if it were possible to do this directly without that hack, i.e. render legible headings in the minimap based on meta-information available about the source?

One approach could be to use named bookmarks to allow the programmer to freely define sections (would require an extension of https://github.com/atom/bookmarks), another to take the symbols already available from https://github.com/atom/symbols-view.

I can only imagine that a minimap enhanced along those lines would quickly supersede most other methods of code navigation.

**Comment by abe33** [comment]
As @fundon proposed it should be done via plugins. Closing this issue now.
